### ISSUE TITLE
Wi-fi interface not being recognized!

### ISSUE THREAD

**Issue by lcsvcn** [dosdude1/macos-catalina-patcher#12]
Wifi is not working after update!

In **About > System Information**:
**WIFI:**
  "CoreWLAN:	13.0 ((null))
  CoreWLANKit:	13.0 ((null))
  Menu Extra:	13.0 ((null))
  System Information:	12.0 (1355)
  IO80211 Family:	12.0 (1200.12.2)
  Diagnostics:	1.0 (910)
  AirPort Utility:	Not Installed"

WWAN:
" No Wireless Wide Area Network could be obtained for this system. WWAN is wireless connectivity through cellular tower technology. Please connect a WWAN device and try again."

My model:
https://support.apple.com/kb/SP632?locale=pt_BR&viewlocale=en_US

My mac version:
10.15.2 (19C57)

**Comment by ijakparov** [comment]
I have the same problem

**Comment by Oda66** [comment]
Same problem here....Any solution found?

**Comment by LogoiLab** [comment]
Same as #44
