### ISSUE TITLE
Safari 14 and Extensions

### ISSUE THREAD

**Issue by NightWestMac** [dosdude1/macos-catalina-patcher#120]
When attempting to enable a safari extension in Safari 14 and, or 14.0.1 in preferences, I get an error "Safari detected an app or service interfering with clicking."

I attempted to do as the apple site (https://support.apple.com/en-us/HT211233) says, and that is to boot into safe mode and attempt it there but I still get the same exact error. Also tried closing the app that the extension was using, didn't make a difference. I decided to reinstall Catalina to get Safari 13.1.2 back and sure enough, it worked just fine. 

Hoping you can fix this soon, as I really like your Catalina Patcher, it brought old Macs back and running with somewhat new software :).

**Comment by justusbeyer** [comment]
Same issue, no solution so far.

**Comment by evilvibes** [comment]
A workaround for this is to edit the file Extensions.plist under `~/Library/Containers/com.apple.Safari/Data/Library/Safari/AppExtensions` and add `<key>Enabled</key><true/>` to the Extension you want enabled. @justusbeyer

**Comment by justusbeyer** [comment]
Thx @evilvibes, that works.

**Comment by Abundance69** [comment]
> A workaround for this is to edit the file Extensions.plist under `~/Library/Containers/com.apple.Safari/Data/Library/Safari/AppExtensions` and add `<key>Enabled</key><true/>` to the Extension you want enabled. @justusbeyer

Hello, when I go to my Safari folder as you describe I only find AutoFillQuirks.plist, I do not find an extentions plist. I am running macOS 10.15.7. Any help would be appreciated.
