### ISSUE TITLE
Graphical glitches make Photos app unusable

### ISSUE THREAD

**Issue by squarus** [dosdude1/macos-catalina-patcher#13]
Above is how Photos app displays when opened. Below is how the image should look like. What causes this?

![Screen Shot 2019-12-26 at 05 23 58](https://user-images.githubusercontent.com/26583909/71454072-f3b17c80-279f-11ea-93d6-b1e230df8d85.png)

![IMG_4958](https://user-images.githubusercontent.com/26583909/71454070-f318e600-279f-11ea-9923-7b5199768787.jpeg)

iMac 20" Mid-2007 with upgraded Core 2 Duo T9500, 3 GB ram, 256 MB ATI Radeon HD 2600 Pro, running 10.15.2 with Catalina Patcher

**Comment by dosdude1** [comment]
This is due to a weird glitch with the legacy AMD video drivers under Catalina. To fix this, use SwitchResX to set the color depth to 24-bit.

**Comment by LvanProosdij** [comment]
You are also missing the « All Pictures » section like here https://github.com/dosdude1/macos-catalina-patcher/issues/4

**Comment by squarus** [comment]
Setting the color depth worked perfectly. Thanks!

**Comment by toshibochan** [comment]
@squarus what you use to change color depth?

**Comment by squarus** [comment]
Create a new display set with the desired resolution, click the cog icon on the bottom while it’s selected and there you will see this line: “Resolution 1920 x 1080 16:9 in Unchanged”, the ‘Unchanged’ part is where you change the color depth.

**Comment by Boldiu-Sama** [comment]
> Create a new display set with the desired resolution, click the cog icon on the bottom while it’s selected and there you will see this line: “Resolution 1920 x 1080 16:9 in Unchanged”, the ‘Unchanged’ part is where you change the color depth.
> […](#)
> On 19 Oct 2021 17:19 +0200, Boldiu-Sama ***@***.***>, wrote: > Above is how Photos app displays when opened. Below is how the image should look like. What causes this? > iMac 20" Mid-2007 with upgraded Core 2 Duo T9500, 3 GB ram, 256 MB ATI Radeon HD 2600 Pro, running 10.15.2 with Catalina Patcher > This is due to a weird glitch with the legacy AMD video drivers under Catalina. To fix this, use SwitchResX to set the color depth to 24-bit. Hey! I have the same issue as squarus, but I couldn't seem to find an option in SwitchResX to control the color depth. Please explain me, how I can manage this issue with SwitchResX, or send me a step-by-step tutorial, because I couldn't find any. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Hey again, I gave it a try, but the option 'Unchanged' can only be set to 'millions', and 'billions' and it doesn't have a different value.

**Comment by squarus** [comment]
It‘s gotta be one of the two. Can‘t remember which at the moment
Am 2. Nov. 2021, 14:42 +0100 schrieb Boldiu-Sama ***@***.***>:

**Comment by summu-b** [comment]
I used this fix and it worked for me.

Several small things that I found out : 
- 24 bits = millions in the mac language (cf. wikipedia)
- to easily change this setting, had to activate it in the menu bar (SwitchResX settings -> launch Deamon)
![Capture d’écran 2021-11-20 à 11 23 17](https://user-images.githubusercontent.com/94741256/142722923-03ab0305-5842-4890-9992-2d8e29254d8c.png)
- for Photos to work, i just had to relaunch it after having made the change
- it seems that the change stays in memory once made, even if the computer is restarted
