### ISSUE TITLE
Overrides Default Boot Volume

### ISSUE THREAD

**Issue by levimcfall** [dosdude1/macos-catalina-patcher#137]
Hello. 

I would really like to be able to make my El Capitan Volume the default for startup, and then use the Catalina one when I need it. I tried changing this in system preferences, but your tool seems to override this.

**Comment by joevt** [comment]
dosdude1 Catalina patcher does not override startup. Change the startup disk using the Startup Disk preferences panel, or the Startup Manager (hold option key at boot, select the item you want to be the default, hold control key and press enter).

OpenCore may override the startup - in that case, boot without it using the Startup Manager.

**Comment by levimcfall** [comment]
Thank You!
