### ISSUE TITLE
nvram boot-args should not be completely replaced

### ISSUE THREAD

**Issue by joevt** [dosdude1/macos-catalina-patcher#14]
I recently tried updating from 10.15 to 10.15.2 by using a patched installer to install over my 10.15 partition. When the first part of the installation completed, it restarted but it didn't seem like it was going anywhere so I forced restart.

I noticed that my boot-args were changed from ```debug=0x144 -no_compat_check maxmem=63488``` to just ```-no_compat_check```. This is a problem because my MacPro3,1 has 64 GB of RAM which causes a slow down unless the ```maxmem=63488``` option exists.

I believe the boot-args should only be changed if the ```-no_compat_check``` option doesn't exist. In that case, the ```-no_compat_check``` option should be appended to boot-args instead of replacing boot-args.

**Comment by startergo** [comment]
Try replacing the `-no_compat_check` with `debug=0x144 -no_compat_check maxmem=63488` in PlatformCheck.m
lines 27, 29 and 31 and recompiling.
`else if ([kernelFlags rangeOfString:@"-no_compat_check"].location == NSNotFound)
    {
        kernelFlags = [kernelFlags stringByAppendingString:@" -no_compat_check"];`
Implies it has been added to an existing flag. Of course this is not directly in NVRAM but in the 
`/Library/Preferences/SystemConfiguration/com.apple.Boot.plist`
