### ISSUE TITLE
No video (GPU Upgrade)

### ISSUE THREAD

**Issue by SewSulle123** [dosdude1/macos-catalina-patcher#142]
I successfully installed catalina on my 2011 imac 12,1. Before the installation I upgraded the graphics card with a k1100m (Flashed With Bootscreens) I was going to use clover for brightness controls but did not do that yet. When I installed catalina I unchecked "Legacy Video Card Patch" (Without doing that I would never have video) With catalina installed I have not video but it boots into macOS. If I reset PRAM video is fine, but every time I turn it on (Restart) I have to reset PRAM. With mojave patcher I don't have this issue.

**Comment by joevt** [comment]
Catalina has a problem with my Mac GTX 680 in a MacPro3,1 where the DisplayPort output doesn't work but does work in Mojave. Maybe there's a WhateverGreen fix? I haven't tried.

**Comment by SewSulle123** [comment]
I did try WhateverGreen with clover but it had no affect. It did work with a pre configured clover file I found. But when I deleted the artificial bootscreen kexts (I flashed my GPU) it stoped working. (It does have Whatever Green though) I guess it could be that same issue.

**Comment by SewSulle123** [comment]
I found this forum with the exact same problem:
https://forums.macrumors.com/threads/dosdude1-macos-catalina-post-imac-gpu-upgrade.2220324/
![Screen Shot 2021-01-29 at 9 25 09 AM](https://user-images.githubusercontent.com/78162557/106286823-140a0100-6214-11eb-8985-1d81cab318ca.png)

**Comment by SewSulle123** [comment]
I've been able to fix this issue using Open Core. I use Open Core for brightness controls, sleep fixes, and to have video on startup. While I have gotten by with Open Core, it is still an issue with the patcher. Also thanks for you're help!
