### ISSUE TITLE
OSX HSierra in MacPro 7.1 2019 ?

### ISSUE THREAD

**Issue by juanpc2018** [dosdude1/macos-catalina-patcher#148]
I dont know why Apple does this,
Apple does Not develop drivers for older OSX to run in Newer machines... New Faster, more efficient machines in older OSX.
Why?
Apple idea seems to be to support 3rd party Software developers income by forced "upgrades", Not by New ideas...

New OSX = New HW = New SW upgrade.
but Not all 3rd party developers continue to develop SW or HW.

By doing that Apple is hurting New HW sales, 
Is Apple a HW company? 

Apple does HW change to avoid SW like Sheepshaver or Hackintosh.
Amiga running MacOS at half the price.
Not the same performace, half the fps, Not professional color corrected display.
But works.

If New machines had drivers for all old OSX since 10.6.8
Nobody would buy used/second hand HW.

people that love old SW today continue to buy used older/second hand HW instead of purchasing New faster, more efficient but No backward compatible HW.

So why Apple does Not want to sell New HW ?

Do they get a $ cut of All the 3rd party SW sales outside Apple store?

Makes No sense to me.

For example: 
Maxtrox MXO2 PCIe video recording HW, 
Has unnoficial drivers that work with Quicktime apps up to HighSierra.
Official Matrox drivers are limited to SnowLeopard, Yosemite drivers work in some SW, but breaks compatibility with All QuickTime Apps like HouseParty, OBS, etc...

ProTools HD10.3.10 and HD PCIe Core cards work flawless up to OSX Mavericks 10.9.5

Mojave breaks compatibility with many older HW.
Catalina breaks compatibility with All 32-Bit.
BigSur is "nice" but Rosetta2 does Not have Rosetta1 PPC compatibility layer from OSX SnowLeopard, is Not even compatible with 32-Bit HighSierra SW.

I understand the idea of 64-bit only.
Its a nice idea, if HW & SW developers upgraded old SW & HW.

Once i tested a Tyan dual Opteron server in Windows 8.1x64
Using asymetric CPUs, CPU0=4 cores and CPU1=16Cores.
The x86 HW emulation does Not work, and all 32-Bit SW fails... 50% of the SW for Windows failed, some way or another.

The alternatives:
VM software like Fusion 12 or Parallels 16, or Oracle VirtualBox, or Codeweavers / Wine / PlayOn Mac, or UTM / QEMU.

Parallels 16 home desktop HDD speed is limited to 75MB/s in a MacPro 5.1 2010, cpus also limited to 4-cores.
Virtualization = payd Downgrade.

Dont know if its just the home Non-Pro version, that has that HHD limit.

some 32-Bit SW running in W8.1x64 does Not work well in Parallels, x86 emulations is broken / incomplete.
= im dissapointed with Parallels.

VMWare Fusion 12 will try.... Seems better.

But Nothing like true Native.

The ideal world would be a MacMini 16GB M1 and UTM/QEMU with 100% compatibility...
TB3 to eGPU PCIe, etc...

But emulations always have bugs, incompatibilities, etc...
From intel to intel emulation has bugs, imagine adding M1 aarch64 / ARMv8 CPU to the mix.
Raspberry Linux runs in M1.
https://corellium.com/blog/linux-m1
But Not 100% yet.

Long ago, my conclusion was:
The fastest computer in the world is useless without Software.

To make a MacPro 7.1 2019 work with HighSierra 10.13.6, 
Video card should be downgraded to a video card compatible with HSierra like Radeon Rx580 8GB or similar.
Radeon VII and 5700xt are Mojave only.

The most compatible video card "No drivers" i have tested in OSX was GTX Titan 6GB, works from Mavericks 10.9.5 to OSX Mojave 10.14.6
but has some visual bugs in OSX HSierra related to 32-bit SW.
OSX SnowLeopard requires HD5770 or HD5870, there are others but unknown like HD6000 exept HD6990.
Or very old FX4800 / FX4500 compatible with OSX Snow or Tiger.

Older OSX does Not support M.2 only SATA-II 3Gbps in MacPro 4.1 5.1 / 2009 2010 2012
would require to boot from USB2.0 external drives.
Booting from USB3.0 would be ideal, but Older OSX like OSX SnowLeopard does Not have USB3.0 drivers built-in, there are 3rd party drivers, but i think are OSX Yosemite 10.10 and ElCapitan only.

MP 7.1 has C612 chipset,
MP 4.1 5.1 has X58 in single CPU trays, 5520 in dual CPU trays.
https://en.wikipedia.org/wiki/Mac_Pro

FireWire400/800 is another issue, OSX SnowLeopard does Not have FW Thunderbolt2 drivers.
Many older HW requires FW to work.
Scaners, Soundcards, etc...

So it seems a pipe dream.

Where is this going to end? 
Cat & Mouse game.

Should i sell everything a move to a forest?

**Comment by juanpc2018** [comment]
tested VMWare Fusion "Player" 12.1
Dissasvantages: 
Requires OSX Catalina
OSX Catalina is an improved/refined version of OSX Mojave. "Very similar"
Parallels 16 works in OSX HighSierra.

Gtx Titan 6GB works in OSX Catalina, No drivers, but has different visual bugs vs. HighSierra. Specially in Sharing configuration menus/options.

Advantages:
Its Free for home users.
Does Not have CPU core limit.
Does Not have HDD speed limit tested with HDTune.

Cons:
CPU in Cinenench R15 1-core test, 
Is 10% lower vs. Native Bootcamp.
Parallels was 5% lower.
Example: From 111 cold test, 109 in hot test to 99 hot test, cold test is imposible in VM.
Maybe because Parallels was using 4 cores only, and Fusion was using 50% of the cores.
Must redo the test with same 4 cores.
Probably both will give same result.

Parallels 16 does Not affect Windows Bootcamp license.
Fusion 12.1 affects license and requires to re-Activate.
If you have an OEM Windows, "purchased in generic white envelope", can only be activated once. 
Only clfancy color Boxed Pro version and virtual Pro license purchased directly from MS web Store allow multiple activations.

So far so good....
USB devices work.
Sound.
Sound seems a bit better in Parallels, maybe because i was using too much cores in Fusion.

Next test would be to try OSX SnowLeopard FireWire and Rosetta in Fusion 12.1
Then Yosemite, and HighSierra.
The others are usually Not important. Unless you use a specific version of macOS Server, maybe El Capitan and Sierra.
macOS Server becomes crap in Mojave.
Installer size is 50% less.
macOS Server has lots of problems in OSX Yosemite, the best macOS Server is between ElCapitan and HSierra.

**Comment by tejasraman** [comment]
STOP RANTING ABOUT MACOS COMPATIBI:ITY ON SUPPORTED MACS IN AN ISSUE TRACKER FOR UNSUPPORTED MACS!

**Comment by tejasraman** [comment]
Oh, and the minimum for MacPro7,1 is macOS Catalina. Sorry.

**Comment by juanpc2018** [comment]
Does Not matter...
installing VMware ESXi or Proxmox
allows to instal any os in any machine, 
much easy than OpenCore, or Clover, or UniBeast, or MultiBoot, or etc...

Runs Virtual but Not Nested.
like other VM: Parallels or VMware Fusion / Workstation Player or VirtualBox or Qemu.
Not 2 OS in 1 machine running simultanously.
is 1 OS running with a compatibility layer.
