### ISSUE TITLE
Can't downgrade

### ISSUE THREAD

**Issue by eat-sleep-code** [dosdude1/macos-catalina-patcher#149]
I installed Catalina on a 2009 Mac Mini.  It ended up having some issues -- crashing programs, slow performance, etc. -- so I want to roll back to a supported OS.   Somewhere in Recovery mode, I managed to nuke my main APFS volume and now I can seemingly either select a drive to boot from or get dumped into the EFI shell.

I created a new bootable USB installer for macOS High Sierra, but after selecting it, I get the prohibitionary symbol.

Is there a way to get the old boot loader back and get back to a supported OS, or is my system completely bricked now?

**Comment by Seb512-YT** [comment]
You need to make a bootable USB installer for El Capitan, as the 2009 Mac Mini can only officially support that operating system and versions before it. If you want High Sierra, you will first need to reinstall el capitain (wiping the HD to macOS Extended) and then use dosdude1's patcher to install/upgrade to high sierra

**Comment by eat-sleep-code** [comment]
This worked.   I also had to remove the hard drive, attach it to my other Mac, and completely erase it.

**Comment by Seb512-YT** [comment]
Good to hear :)

**Comment by vebaev** [comment]
I have similar issue with my Mac mini 2011, I have installed on a usb and made it bootable El Capitan (which should be the last supported OS for the mini). In the usb installer disc utility I formatted the internal SSD to GUID journaled extended, then installed El Capitan. But on boot it just show a white/gray screen? Any tip how to solved it? (previously I had dosdude1 Catalana).
