### ISSUE TITLE
just write down your ssid and password, no matter others. > Thank you very much. I done like this,

### ISSUE THREAD

**Issue by bubifengyun** [dosdude1/macos-catalina-patcher#151]
> Thank you very much. I done like this,
> 
> ```shell
> % networksetup -listnetworkserviceorder
> An asterisk (*) denotes that a network service is disabled.
> (1) Ethernet
> (Hardware Port: Ethernet, Device: en1)
> 
> (2) FireWire
> (Hardware Port: FireWire, Device: fw0)
> 
> (3) Wi-Fi
> (Hardware Port: Wi-Fi, Device: en0)
> 
> (4) Bluetooth PAN
> (Hardware Port: Bluetooth PAN, Device: en2)
> ```
> 
> then I find my wifi Device name is `en0`,
> 
> ```shell
> % sudo networksetup -setairportnetwork en0 <ssid> <password>
> ```

Thanks!!!

Any way to add wifi with hide ssid and no password ? like "my wifi"

_Originally posted by @itsalb3rt in https://github.com/dosdude1/macos-catalina-patcher/issues/131#issuecomment-800666941_

**Comment by Seb512-YT** [comment]
I wouldn't think so - is there any specific reason why you want to hide the SSID and Password?

**Comment by itsalb3rt** [comment]
> I wouldn't think so - is there any specific reason why you want to hide the SSID and Password?

Imagine that you have a Wi-Fi network for Wi-Fi security cameras, do you want to have a Wi-Fi network like that shown?

**Comment by Seb512-YT** [comment]
No but I mean, what are you trying to set up? The airport card on your Mac? If you are trying to show people a problem then just blur out the SSID

**Comment by itsalb3rt** [comment]
I just try to connect to a hidden wifi network is all, it was not me who created the issus.

**Comment by Seb512-YT** [comment]
ok, I don't know why whoever made the issue did so , as it was already posted on another issue's comments. bubifengyun please close it to avoid further confusion - thanks

**Comment by bubifengyun** [comment]
sorry, I comment in mobile. Maybe something wrong.
