### ISSUE TITLE
Video Stream won't work (Zoom or Microsoft Teams

### ISSUE THREAD

**Issue by pqhcker** [dosdude1/macos-catalina-patcher#155]
Hi... I found an issue with Microsoft Teams or Zoom. When I activate the camera so that the receiver can see me, everything works fine for the receiver, but as a sender, I can't see anyone's camera. It only shows black screen. Both audio and video work correctly

**Comment by SzosszeNET** [comment]
Have you installed the patch? http://dosdude1.com/catalina/ bottom under FAQ, last point

**Comment by LogoiLab** [comment]
duplicate of #89

**Comment by kptkip** [comment]
Another easy solution I found:
 https://forums.macrumors.com/attachments/tccplus-wrapper-hotfix-zip.903316/ 

- Download and run it
- Select which application you want to modify 
- Select "Microphone" and "Camera" (one procedure per app and device type)
- open the program twice and it works! 

I authorized chrome, slack and zoom for camera and mic :) 

Hope this helps people in the future
