### ISSUE TITLE
Unable to boot into the installer

### ISSUE THREAD

**Issue by bopow** [dosdude1/macos-catalina-patcher#18]
Thank you so much for making this!
I’m running a mbp 2011 early with an ssd and 8gb of ram working flawlessly with mojave. 

Now i am trying for days to get catalina to work. 

I have updated the bootrom to the latest version 81.00 somethingsomething and i updated the smb to 1.68f99 but the smb 1.7 isn’t for my device? Anyhow i managed to install mountain lion on the mbp and install it through the packages off off apples website so the bootrom has been updated. 

The Process:
Download the catalina patcher and put itninto applications fromtbere roght click and open and open again. 

Download catalina
Run disk utility and format my usb (or a partition on the ssd) and format it to macos extended journaled
Now i let the installer make the usb
I check the log for anything abnormal ( in a sense abnormal in comparison to the mojave patcher)
It succeeds and i turn off the mbp 8,1
Hold alt and select the desired catalina boot usb and hit enter
Then it goes upto ~60% and then it continues very slowly untill it halts at 99% and it stays there indefinitly..

I tried different usbs and even the internal ssd with a macos journaled partition to boot the installer..i’m out of idea’s here

Any help is much appreciated!

I’m trying to archieve a fully functional upto date mbp with continuity, handoff support/unlock with iphone or apple watch etc etc

Thnx

Edit: downloaded a catalina dmg from an other website disabled the automatic post install patches and its now booting further. 

Now i get; An error occurred while preparing the installation. Try running again
I googled i did set the date correctly so that shouldnt be a problem
I also tried redownloading sierra again through the patcher but its bot able to download catalina?

**Comment by pledge** [comment]
I had the same issue with a mid-2011 mac mini. I had made the boot disk using High Sierra on the mini itself. When I made the boot disk on another Catalina MBP it worked. I did use a different USB pen drive as well.

**Comment by LogoiLab** [comment]
Your issue has been closed because it is a common problem that can be remedied by taking the appropriate steps or just reading instructions: http://dosdude1.com/catalina/

Your comment has also been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.
