### ISSUE TITLE
iMac 11,2 - "An error occurred while applying patches (1)."

### ISSUE THREAD

**Issue by jnennemann** [dosdude1/macos-catalina-patcher#19]
I have tried repeatedly, sometimes completely from scratch (reformatted USB drive), without any success. I keep getting this error on an iMac 11,2. Anything that I may try? It does not create a bootable system after it restarts.

**Comment by lsustar** [comment]
I am having the same issue on Mac Pro 3,1.

**Comment by dosdude1** [comment]
Post-install patches should be applied automatically, and do not need to be applied manually in most circumstances. If an error occurs while applying patches, chances are there is not a complete copy of Catalina on the volume.

**Comment by 2tama3** [comment]
> reformatted USB drive

What format type did you choose?

**Comment by lsustar** [comment]
Thanks very much for the responses. I did use the Catalina Patcher Web site to download the Catalina volume. I also used macOS Extended Journaled format for the USB, as instructed.

**Comment by 2tama3** [comment]
Has this USB media been Disk Utility Full initialized ?

**Comment by lsustar** [comment]
No, the USB media has not been Disk Utility Full initialized. I will pursue
that angle. Thank you.

**Comment by kabodonchan** [comment]
Full format of usb media with Extended Journaled it's the solution?
Thx.

**Comment by MacIsUs** [comment]
Ok!  I may have found something out. After trying to install many times I discovered that you need to go to the efi boot option on your installed hard drive.  It finishes the install and then everything works perfectly! I hope my 10h of suffering will help someone else out!

**Comment by LvanProosdij** [comment]
> Ok! I may have found something out. After trying to install many times I discovered that you need to go to the efi boot option on your installed hard drive.

Great! But could you be more precise ?

**Comment by MacIsUs** [comment]
Sorry commented in my excitement. 
So after you make the installer tool and go through the normal install procedure, hit the alt(option key at start up and chose your drive where you installed the OS, do not go back to the installer it’s self. For me it showed up as EFI BOOT. I went into that and it finished the Catalina install and patches automatically. 
My USB installer drive was formatted as APFS then used dos dudes tool to creat the installer on my USB drive. 11gb is the needed portion size as with 10gb it failed. (Useful if you have multiple installer on the same drive). Hopefully this info helped others out.  Any other questions if I missed a detail I’ll try to reply too. 
Not that he’ll see it but want to say thank you to dosdude for making yet another amazing too to undo the stupidity Tim Cook does with his early obsoleting of our machines. Why shouldn’t an 8 core 3,1 Mac Pro with 32gb of ram natively support it? Seriously!  My only other wish list is for 32bit support to remain.  I have thousands of dollars worth of software I still use so my main machine is still on Mojave. If anyone knows a way to add 32bit back I’d love to hear about it (other than running dual OS or running an OS within an OS in parallels.  Thanks!

**Comment by kabodonchan** [comment]
I solved problem in this way: I installed first High Sierra and installer told me that firmware update was required. I have installed firmware update by pressing the button as it said me and I installed then High Sierra. After this I initialized HD with APFS file system and all the Catalina installation process by dosdude works fine.
Thx dosdude!

**Comment by brunsik** [comment]
![Zrzut ekranu 2020-03-27 o 19 48 36](https://user-images.githubusercontent.com/59973081/77789779-f738f600-7063-11ea-8d6a-4b47f1333c53.png)

Any ideas why is that appears?
It occurs every time I try install these:

![Zrzut ekranu 2020-03-27 o 19 49 46](https://user-images.githubusercontent.com/59973081/77789853-1e8fc300-7064-11ea-81b2-630470f8eaf7.png)

No success, at all.
My model: MacBookPro5,2
BTW all other stuff work like a charm.

**Comment by SolidStill** [comment]
Which version of Catalina are you installing? 15.3?

**Comment by brunsik** [comment]
I use 10.15.1 version since a long time and since then above error persist.

**Comment by SolidStill** [comment]
Ok, well I'd guess that the patch updates are designed to be installed on a Catalina version that is more recent than 15.1 - ie 15.2 or 15.3 - but I'm not sure. I had Catalina running on my MBP 5,2 but I was running the latest patch updates on 15.3. I'd try backing-up and updating your OS 15.3 (NOT 15.4), but you might want to get advice from @dosdude1 or someone else knowledgeable first.

**Comment by brunsik** [comment]
Thanks. So it might be a high time to update the system :)

**Comment by SolidStill** [comment]
Backup if needed though! Don't trust my opinion blindly, I'm an amateur!
