### ISSUE TITLE
Catalina installer damaged error

### ISSUE THREAD

**Issue by Oda66** [dosdude1/macos-catalina-patcher#20]
Hi,
I'm trying to use the patcher to get Catalina running on a late 2009 Mac mini, that has a Fusion drive formatted as APFS.
All process works fine, patcher is created, and boots flawlessly, until I actually select to install Catalina, then I get an error message that installer file is damaged and can't be opened. That installer was in fact downloaded "internally" using the patcher. I tried to replace the installer, I created a new patcher, used both a thumb drive and a SATA/USB drive, and I always get the same error. The installer BTW is formatted using the "classic" extended file system.
Is this a know issue? any suggestions? 
Cheers!
Oded

**Comment by dosdude1** [comment]
Have you verified you're using the latest Patcher version? It is important that you do so when using the latest Catalina Installer app.

**Comment by Oda66** [comment]
Sure, I downloaded the latest patcher version directly from your website, then used it to download Catalina but I keep getting that message. After numerous attempts I opted for the Mojave option, and installed it on an APFS Fusion drive I crated on my 2009 Mini,+ 8GB RAM = great and modern system. BTW, I also had troubles here with some patcher error messages so my walk around was to create a clean Mojave system on flash drive using a 2013 machine, then patch it from that same machine, boot the mini from it,  carbon copy the OS to an APFS volume (or whatever they call it now) on the fusion drive, and then patch that new volume (or whatever they call it now) to have it "blessed" and all the magic that you do there. Worked like a charm. I though of doing the same with Catalina on a separate volume as Apple claim it is possible, but Carbon Copy Cloner gave me some horror messages about two OSs in the same container, and also Catalina itself is residing now on two separate volumes (XYZ & XYZ data) and I'm not sure how to treats it.  Sorry for the long text, hope it may be useful to someone.

**Comment by rkistner** [comment]
I'm getting the same issue. Maybe it's something with the 10.15.3 version (released 28 Jan)?

**Comment by jmslcs** [comment]
I’m having this same issue. Using the patcher you install Catalina and I get the error mentioned above about it being damaged. Issue with the certificate I think?

**Comment by Oda66** [comment]
A Catalina patcher work around update. (you'll need a Catalina supporting Mac and usb to data case/connector)
By using the case I hooked the to-be internal SSD of my Mac mini 3,1  to a Catalina supported MacBook, and used the Catalina installer (which I actually downloaded through DOSDUDE's patcher) to install Catalina. After hand, I booted from that drive, completed the instalation and then rebooted back using the internal MacBook drive. Now I used the Post install patcher (you need to dig a little in the patcher content to find it) and (important!!!!) changed the patching profile to  your relevant machine. The drive then booted the Mac mini with no problem. 
ONE big problem.... WIFI doesn't work (nor shows as an option), so unless there's a solution or you don't need wifi, check it before installing the drive inside your unsupported device.

**Comment by dosdude1** [comment]
The BCM4321 patch contains a detection routine, so it installs ONLY if a BCM4321 card is present on the machine the post-install tool is running on. As such, you MUST run the post-install tool on the Mac Mini itself to get the necessary BCM4321 patch to install. Once done, WiFi will work fine.

**Comment by Oda66** [comment]
Thanks! well appreciated. Now I have Corona (oops, I meant "Catalina") running on my 2009 Mac mini like a charm.
BTW, the patcher didn't do the job, tried numerous times from both Mojave/Catalina boot volumes. At the end used the patch update control panel, which opens a list of installed patches, right clicked the BCM4321 option, then the magic happened. 
BTW 2, I noticed there's a Sidecar icon in the Mac mini's control panel, didn't check if it works, but I wonder if one of the patches can enable sidecar on may late 2013 MBP. If so, which one?
Regards from Israel,
Oded

**Comment by darkestlondon** [comment]
I have the same issue (installer is damaged error message) also on a 2012 Mac Pro 5,1 - with the latest 1.3.0 patcher. I have tried downloading the Catalina Installer through the patcher app and also direct from Software Update on a Catalina compatible mac. I have also tried creating installer boot on two different USB keys and a USB hard drive.
I instead installed Catalina onto a USB drive with a Catalina compatible mac and then booted the 5,1 from the Patched installer USB to try and run the post install patches on the actual machine - but the post patch install doesn't function - press the button and nothing.
Could it be to do with the 10.15.3 installer being different?
Thanks,
Richard

**Comment by mistakster** [comment]
@dosdude1, hi! I also faced the same issue today.

iMac late 2009, patcher 1.3.1, Catalina installation was downloaded using the patcher,

BTW, I tried to install 10.15.1, 10.15.2, 10.15.3 and got the same error. And I tried with and without a network connection — the same error.

Please, could you suggest anything? I can provide any additional information you need.

**Comment by mistakster** [comment]
Wow, I’ve finally managed to run the installer! Here are my findings.

## Wrong actions

1. Create a bootable USB on iMac with macOS High Sierra (10.13).
2. Boot from this USB.
3. Open Disk Utility and format HDD with APFS.

At this step, I usually get an error like this:

```
Created new APFS volume
Mounting APFS volume
Couldn't mount the disk
```

Although HDD was formatted, the volume remains unmounted (it's gray in the list)

4. Start the installation — a popup “Catalina installer damaged error” appears.

## Correct actions

1. **Create a bootable USB on macOS Mojave (10.14)**. I used MacBook Pro 2019.
2. Boot on iMac using this USB stick.
3. Format HDD — everything worked correctly at this step, and the new volume appeared mounted for me.
4. Start the installation.

I have no idea why this workflow worked this time for me. I created the bootable USB on MacBook Pro for macOS Catalina 10.15.1 before. But the installer showed the error as described above.

**Comment by cl0rm** [comment]
For me it didn't work on a iMac 8,1.
I do not have any newer Macs.
Created the installer on this iMac using OSX 10.11

**Comment by luminarycrush** [comment]
> Wow, I’ve finally managed to run the installer! Here are my findings.
> ## Wrong actions
> 
>     1. Create a bootable USB on iMac with macOS High Sierra (10.13).
> 
>     2. Boot from this USB.
> 
>     3. Open Disk Utility and format HDD with APFS.
> 
> 
> At this step, I usually get an error like this:
> 
> ```
> Created new APFS volume
> Mounting APFS volume
> Couldn't mount the disk
> ```
> 
> Although HDD was formatted, the volume remains unmounted (it's gray in the list)
> 
>     1. Start the installation — a popup “Catalina installer damaged error” appears.
> 
> 
> ## Correct actions
> 
>     1. **Create a bootable USB on macOS Mojave (10.14)**. I used MacBook Pro 2019.
> 
>     2. Boot on iMac using this USB stick.
> 
>     3. Format HDD — everything worked correctly at this step, and the new volume appeared mounted for me.
> 
>     4. Start the installation.
> 
> 
> I have no idea why this workflow worked this time for me. I created the bootable USB on MacBook Pro for macOS Catalina 10.15.1 before. But the installer showed the error as described above.

I am having the same problems as everyone else here.  The machine is an iMac mid-2011.  I tried the above solution listed as the Correct Action (created the Catalina bootable disk from my Air running Mojave).  While the iMac saw it as a bootable the boot never completed.  

I went back to Mac OS Patcher Mojave which worked fine.  

I should note that I tried a few different removable disks - usb stick, SD card in a USB reader, USB external SATA drive during this experimentation.  In the end I had the most success with the latter.  Often the sticks and cards weren't seen as bootable - they just seem much less reliable for performing installs in general.

**Comment by LogoiLab** [comment]
Your issue has been closed because it is a common problem that can be remedied by taking the appropriate steps or just reading instructions: http://dosdude1.com/catalina/

Your comment has also been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.
