### ISSUE TITLE
Safari 15.6.1 Graphics Issue after 1.4.5 update via System Preferences

### ISSUE THREAD

**Issue by kajohnson04** [dosdude1/macos-catalina-patcher#202]
Apparently the Catalina Patcher had an update pushed out yesterday. I went ahead and installed it. I was prompted fo reboot the machine. The reboot hung, so I restarted the machine. Now Safari 15.6.1 will load the start page without issue, but if you try to load in any page, this is what it looks like.

Mid 2010 MacBook Pro 17"' 8GB RAM / 4TB SSD.
![Screen Shot 2022-09-08 at 8 55 26 AM](https://user-images.githubusercontent.com/113142359/189224396-f1fffe2d-4d25-498d-8d58-2075528dfca2.png)

Artifacting only in Safari and Stellar (Reddit app) . Machine appears to be functioning fine in every other respect. Music doesn't launch either, but I use Safari more often than not. Might be connected to "Added much-needed improvements to Legacy Video Card Patch for non-Metal video cards," as it functioned fine before the update.  

![Screen Shot 2022-09-08 at 8 55 26 AM](https://user-images.githubusercontent.com/113142359/189223095-cf60e84b-39e4-4012-b3da-b65da6d41082.png)
THIS IS NOT YOUR HELPDESK, WE HAVE FORUMS FOR A REASON. Please only file an issue here for code-related problems. This is not an issue system for resolving issues with using the compiled binaries, or discussing functionality issues with Catalina on your unsupported machine.
- [ ] I understand

**Comment by tejasraman** [comment]
Fixed in 1.4.6

**Comment by kajohnson04** [comment]
Got an update notification a few minutes after I posted. All is well again.

**Comment by tejasraman** [comment]
Great. Thanks!
