### ISSUE TITLE
My Mac can't load after update

### ISSUE THREAD

**Issue by Allespro** [dosdude1/macos-catalina-patcher#203]
Hi, I use Macbook pro late 2011
After last update in verbose mode (cmd + v) I got this error. I can't find any solutions, maybe someone have same problem. The one solution I see, is reinstall system

```
AMFI: SIP is off, allowing core dump for pid xxx
AMFI: SIP is off, allowing core dump for pid xxy
AMFI: SIP is off, allowing core dump for pid xxz
```

**Comment by c1001r** [comment]
Have the same problem that the MacBook (5,1) won't startup after installing Legacy Video Card Patch and Library Validation Disabler Patch. The solution for me is to boot with the installation USB and reinstall Legacy Video Card Update. That is the old version and after reboot the Patch Updater will prompt the available updates. Apple Music app won't work for now as I guess that is the Library Validation Disabler for.

**Comment by Allespro** [comment]
> Have the same problem that the MacBook (5,1) won't startup after installing Legacy Video Card Patch and Library Validation Disabler Patch. The solution for me is to boot with the installation USB and reinstall Legacy Video Card Update. That is the old version and after reboot the Patch Updater will prompt the available updates. Apple Music app won't work for now as I guess that is the Library Validation Disabler for. 

Will try, thanks. I'll write if I can restore the system

**Comment by Orfait** [comment]
Had same issue.
According to this post : https://forums.macrumors.com/threads/macos-10-15-catalina-on-unsupported-macs.2183772/post-28232726

I started in single user mode and ran:

```
mount -uw /
nvram boot-args="-no_compat_check amfi_get_out_of_my_way=1"
reboot
```

Booted again.
But I clearly don't know if it is the good way to fix the issue.

Hope this helps

**Comment by Allespro** [comment]
> Had same issue.
> According to this post : https://forums.macrumors.com/threads/macos-10-15-catalina-on-unsupported-macs.2183772/post-28232726
> 
> I started in single user mode and ran:
> 
> ```
> mount -uw /
> nvram boot-args="-no_compat_check amfi_get_out_of_my_way=1"
> reboot
> ```
> 
> Booted again.
> But I clearly don't know if it is the good way to fix the issue.
> 
> Hope this helps

This helps! Thank a lot!

**Comment by wolfwolfswinkel** [comment]
Same issue on a late 2009 iMac; the above workaround helped me as well.

**Comment by dosdude1** [comment]
Sorry for any issues caused by that update, I realized there was an issue with the method in which it was being applied, causing the desired changes to fail to be applied properly. This has been resolved now.

**Comment by Orfait** [comment]
@dosdude1 can you confirm that how I fixed this issue is correct and does not break anything?

**Comment by dosdude1** [comment]
The only thing that will break is the ability for apps to ask for permissions, such as mic, camera access, etc. Applying the fixed Library Validation Patch (or re-install via Patch Updater), will resolve any issues.

**Comment by LuisCifaldi** [comment]
Hi Dosdude. I had the same problem on a 2009 white mac. Now, I need to instruct over phone the owner of the computer. The problem is that this person (my little sister has not the usb catalina installation). So, in order to get the new patch, it is fine to use the code mount -uw ..... as the member Orfait recommended on single user mode and then once the computer will  log in I can re-download the new patch? Or maybe you can suggest another work around? Thank you very much Luis.

**Comment by b-abdenoure** [comment]
I have a late 2011 macbook pro 17", same problem and @Allespro solution work for me, when the mac reboot i had same update notification but i didn't going to install it since i du the fix and the update libraries..... the same problem.
Well done @dosdude1 for the work and the bigest help you give to old mac owner.

**Comment by TejashM** [comment]
I have a late 2009 iMac. I have the same problem and I can't figure out how to get my mac to start. I cannot even start it in safe mode. The workaround as suggested by user @Orfait also does not work since I can't get beyond the apple logo.

**Comment by b-abdenoure** [comment]
> I have a late 2009 iMac. I have the same problem and I can't figure out how to get my mac to start. I cannot even start it in safe mode. The workaround as suggested by user @Orfait also does not work since I can't get beyond the apple logo. 
> 
> 

you can insert the code proposed by @Orfait with opening the terminal in boot install session or recuperation session, then wrote the code and your mac can start after reboot

**Comment by c1001r** [comment]
> The only thing that will break is the ability for apps to ask for permissions, such as mic, camera access, etc. Applying the fixed Library Validation Patch (or re-install via Patch Updater), will resolve any issues.

@dosdude1 Thanks for the new release! It is working now perfectly on MB 5,1. You have done such an important contribution to many of us using old macs that would not be useful anymore

**Comment by TejashM** [comment]
> > I have a late 2009 iMac. I have the same problem and I can't figure out how to get my mac to start. I cannot even start it in safe mode. The workaround as suggested by user @Orfait also does not work since I can't get beyond the apple logo.
> 
> you can insert the code proposed by @Orfait with opening the terminal in boot install session or recuperation session, then wrote the code and your mac can start after reboot

Sorry for my ignorance but I cant even get past the "apple" logo. So I cant access terminal and hence cant insert the code.

**Comment by Orfait** [comment]
Boot holding cmd+S keys.

**Comment by TejashM** [comment]
> Boot holding cmd+S keys.

Thanks a ton. It works now. Thanks @dosdude1 for the amazing catalina patch.

**Comment by jottwe** [comment]
Doing the after installation patches once again did the job. But just for the case someone can't boot or can't reach command line:

MacMini3,1 stuck at logo and 100% progress bar after update. Did pram reset and it stuck at logo and 0% progress bar. Single user stuck at pci configuration and booting from catalina patcher stick stuck at logo and 0% progress bar as well.

Workaround: Booting once from OS X Installation DVD (doesn't have to match the hardware!), exit before installation, reboot from catalina patcher stick,  go through after installation patches ... et voila ... everything is fine again.

**Comment by LuisCifaldi** [comment]
I am trying the code  mount -uw /nvram boot-args="-no_compat_check amfi_get_out_of_my_way=1"reboot. 
the result string says unknown special file or file system. When I reboot still blocked on black screen with the logo and white bar. I am doing something wrong? maybe the code I am writing is wrong. thanks Luis

**Comment by Allespro** [comment]
> I am trying the code  mount -uw /nvram boot-args="-no_compat_check amfi_get_out_of_my_way=1"reboot. 
> the result string says unknown special file or file system. When I reboot still blocked on black screen with the logo and white bar. I am doing something wrong? maybe the code I am writing is wrong. thanks Luis

How do you do that?

You need boot holding cmd+s

**Comment by LuisCifaldi** [comment]
yes, I am doing in single mode !  I am  in doubt about the code. Orfait wrote :
mount -uw /
nvram boot-args="-no_compat_check amfi_get_out_of_my_way=1"
reboot            i need to start new line as Orfeit or I can write consecutive mount -uw /nvram boot-args="-no_compat_check amfi_get_out_of_my_way=1"reboot

**Comment by LuisCifaldi** [comment]
maybe spacing is wrong?

**Comment by LuisCifaldi** [comment]
Sorry for my ignorance maybe i need to write: 
mount -uw / and press return    
nvram boot-args="-no_compat_check amfi_get_out_of_my_way=1" and press return 
reboot and press return ? let me know
Luis

**Comment by b-abdenoure** [comment]
yes its correct

**Comment by LuisCifaldi** [comment]
After the reboot still stuck on white apple! what I am doing wrong. Please help
![6965f441-69d8-48c7-9068-8c217da705cd](https://user-images.githubusercontent.com/113259696/189537324-28a20ef0-fc4c-4806-849e-98bd5384ded3.jpg)

**Comment by b-abdenoure** [comment]
reboot with pressing cmd + r untill you a globe that enter you in recuperation session or reboot with pressing alt.
i can't hep you more than that

**Comment by LuisCifaldi** [comment]
in recovery mode ? and after I enter in recovery mode? what I do?

**Comment by b-abdenoure** [comment]
on the top menus, select terminal in one of them, them wrote the code

**Comment by LuisCifaldi** [comment]
ok

**Comment by LuisCifaldi** [comment]
Your help it gives me hope. Thank you again! I am trying now

**Comment by LuisCifaldi** [comment]
nothing!

**Comment by LuisCifaldi** [comment]
Because the code is not working on my mac, is it a way to resolve using the USB caterina patcher installer? Thank you. Luis

**Comment by Allespro** [comment]
> Because the code is not working on my mac, is it a way to resolve using the USB caterina patcher installer? Thank you. Luis

Still you have `AMFI: SIP is off` error in verbose mode (cmd+v)? Or something another?

**Comment by LuisCifaldi** [comment]
Hi Allespro, I did not check via verbose to see the error status ! But maybe with the installation usb I can revert and reinstall the patch ?

**Comment by LuisCifaldi** [comment]
I am going to try tomorrow the verbose and let you know as I need to instruct the owner of the computer.

**Comment by LuisCifaldi** [comment]
Here the image showing the error as you said.

![7bd71374-b06e-4954-94d4-ba6b866a4a4c](https://user-images.githubusercontent.com/113259696/189641759-7e3f27e2-60b7-40ad-96d3-28b3732ba29a.jpg)

**Comment by LuisCifaldi** [comment]
Any help with this? The code still not working for me. I will try with the usb installer as the member C1001R . Do you know how I need to operate? thank you.

Luis

**Comment by Allespro** [comment]
> Any help with this? The code still not working for me. I will try with the usb installer as the member C1001R . Do you know how I need to operate? thank you.
> 
> Luis

Check `boot-args` in single mode, if they are not the same as in the command, then you enter the command incorrectly
https://i.ibb.co/PWZHWzj/IMG-20220913-110108-250.jpg
That's my old `boot-args`

**Comment by LuisCifaldi** [comment]
Thank you for your answer. Sorry Allenpro I did not get it or maybe a bit confused. I need to open in single mode and check as you said the line where it should be written as in your images, and check how the code is written? and copy it ? in your old boot-args cannot find inverted commas and space is different colse to the =. ?    thank you Luigi

**Comment by LuisCifaldi** [comment]
Dear Allespro, I attach the image where it shows in the single mode the code : Can you check if it is wrong? 

![image zx](https://user-images.githubusercontent.com/113259696/189907314-cd5ef4f8-6a0c-4a8d-a6bd-ff5371cb9c9f.jpg)

**Comment by Allespro** [comment]
> Dear Allespro, I attach the image where it shows in the single mode the code : Can you check if it is wrong? 
> 
> ![image zx](https://user-images.githubusercontent.com/113259696/189907314-cd5ef4f8-6a0c-4a8d-a6bd-ff5371cb9c9f.jpg)
> 

yes, the option is set incorrectly

**Comment by LuisCifaldi** [comment]
So, I am guessing what I am doing wrong. I have copied the 3 lines as mentioned above. 
1) mount -uw /
2) nvram boot-args="-no_compat_check amfi_get_out_of_my_way=1"
3) reboot

**Comment by LuisCifaldi** [comment]
Done!!!!! very happy. I follow c1001r member instruction! Usb installer reapplied the patches and back to work. ! thank you to all of you.
