### ISSUE TITLE
Catalina Patcher / Library

### ISSUE THREAD

**Issue by antoinemelchior** [dosdude1/macos-catalina-patcher#205]
Hy. I'm video editor and I'm French. Sorry for my bad english.
I have a MacPRO 2010 with CATALINA 10.15.7

I've had an issue with the last Update of MacOs Catalina Patcher.
Few days ago I received a new Patch update called : " LIBRARY VALIDATION DISABLER PATCH ".
I've accept this update.

Now the app " MUSIC " can't open anymore.
How can i fix this... ? I'm lost. I would like to delete this update patch because
before that I installed it, eveythings worked well.

If you have a solution. Thank you for your help.
Cheers,
Antoine from France.... and lost with his update patch

**Comment by dosdude1** [comment]
I just released a new version that will revert those changes.

**Comment by antoinemelchior** [comment]
Thanks... But What should I do now ? Will you send us the new update patch ?

**Comment by antoinemelchior** [comment]
Hy. Thank you sooooo much. It works well again. I'm so happy. You cant imagine.
You save my Music app.
