### ISSUE TITLE
1.4.6 downloads Catalina 15.7.02, not 15.7.03?

### ISSUE THREAD

**Issue by sbytnar** [dosdude1/macos-catalina-patcher#207]
Just ran macOS Catalina Patcher 1.4.6. It downloaded Install macOS Catalina 15.7.02.
Should it be downloading 15.7.03?

**Comment by dosdude1** [comment]
Fixed with release 1.4.7, check and verify.

**Comment by sbytnar** [comment]
Verified fixed in 1.4.7: it downloads 15.7.03.
