### ISSUE TITLE
Automatic dark/light mode setting won't be kept

### ISSUE THREAD

**Issue by genfersee** [dosdude1/macos-catalina-patcher#21]
Dear all,

In settings app, general, appearance, when I set dark/light mode setting to automatic, this setting is always reset each time to dark mode after closing the settings app and restarting the setting app.

I am running macbookair4.1.

Kind regards

**Comment by ach881** [comment]
Same issue on MacBook Pro 8,1

**Comment by charlesomer** [comment]
Seems to ignore "auto" and just uses the last selected value (light/dark). (MacBookPro5,5)

**Comment by dosdude1** [comment]
This is a side-effect of the Legacy Video Card Patches, and unfortunately cannot be resolved at this time.
