### ISSUE TITLE
Returning to macOs Utilities

### ISSUE THREAD

**Issue by Tommlyn** [dosdude1/macos-catalina-patcher#24]
Hello everyone, I am trying to install on a late 2009 white Macbook.
Every time i try to install Catalina using the patcher, it goes to the screen “installing to selected volume” and when its supposed to restart, it does, but instead of booting into the second part of install, it boots back to the Utilities. When i look in the Disk utility, it shows that the disk i selected to install macos to has about 8gb used. Does anybody know what might be the issue?

**Comment by dosdude1** [comment]
Your system firmware is not up to date. Please read and follow the Important Info section.

**Comment by Menniac** [comment]
Hey there! First of all thanks to dosdude1 for his amazing work! I had already installed the High Sierra Patch on my iMac 8.1 and it worked nicely all the way. 
Now I update to Catalina for some software which was no longer available for High Sierra and I had the same issue as described by Tommlyn. In my case (I think, I'm not an expert) it wasn't the firmware, but it seemed to to be the external drive that I used as a boot device. The machine always booted back to Utilities as long as it was connected. When I shut down the Mac and started it without any connection to the external drive, it went to the second installation process and finished it all the way.
So maybe this helps people having the same issue. Thanks again!

**Comment by BigBenM** [comment]
> Hey there! First of all thanks to dosdude1 for his amazing work! I had already installed the High Sierra Patch on my iMac 8.1 and it worked nicely all the way.
> Now I update to Catalina for some software which was no longer available for High Sierra and I had the same issue as described by Tommlyn. In my case (I think, I'm not an expert) it wasn't the firmware, but it seemed to to be the external drive that I used as a boot device. The machine always booted back to Utilities as long as it was connected. When I shut down the Mac and started it without any connection to the external drive, it went to the second installation process and finished it all the way.
> So maybe this helps people having the same issue. Thanks again!

Bro! Literally wasted hours trying to figure this out.... I have ZERO clue why this didn’t occur to me, thank you very much!

**Comment by LogoiLab** [comment]
Your issue has been closed because it is a common problem that can be remedied by taking the appropriate steps or just reading instructions: http://dosdude1.com/catalina/

Your comment has also been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.
