### ISSUE TITLE
FileVault useable?

### ISSUE THREAD

**Issue by chiel1980** [dosdude1/macos-catalina-patcher#32]
Does the FileVault encryption work on the newer Catalina 10.15.4 with an old MBP (using the APFS patch)? Should it work?
I am afraid to test it as I read in some older forum posts that it gave people kernel panics and such..
Really looking forward to encrypt my disk :) 

Thanks for the great patcher solution!

**Comment by LogoiLab** [comment]
Your comment has also been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.
