### ISSUE TITLE
Camera not working on zoom.us app

### ISSUE THREAD

**Issue by pauloens77** [dosdude1/macos-catalina-patcher#36]
The people connected to me trough zoom.us app can see my image, but the image from the camera I can't see on my mac.
Other apps like photo booth show the camera image normally.

It wasn't working on Mojave patcher, then I decided to upgrade to Catalina to make it work and it's not working too.

Macbook pro 8,1 - 13" screen

**Comment by starmessage** [comment]
I also have this problem with Catalina 15.2
macbook model: 13-inch, Mid 2010
Model ID: MacBook7,1
Model Number: A1342

**Comment by danoxi** [comment]
I also have the same problem with Catalina 15.4. 
I have two old macs, and both have the same problem - no video from my camera and no video from others (they see me perfectly and I have ability to record video, and it works). 
Macbook pro 5,2 17"- 2009
imac 11,1 27" - 2009

**Comment by Kshukla** [comment]
Same issue with the screen display when someone shares there screen.

**Comment by dosdude1** [comment]
You need to use an older version of Zoom, that does not utilize Metal rendering (which the hardware in older machines does not support). A version that works can be downloaded here: https://d11yldzmag5yn.cloudfront.net/prod/4.5.5757.1110/Zoom.pkg

**Comment by pauloens77** [comment]
Thank you so much! Worked fine now!!!

**Comment by teletoeffel** [comment]
Thank you very much, this hint helped me a lot. Because of the Conora pandemic, lectures at my university are held via zoom. The lecture period started yesterday, April 20th. Without the link I would have been lost!

**Comment by madamadami** [comment]
Thankk you as well!

**Comment by jasonkim-jk** [comment]
There is a patch for non-Metal GPU from dosdude1.
See this link and patch the shell script.
I downloaded the lasted zoom version, it works after applying the patch.

https://forums.macrumors.com/threads/macos-10-15-catalina-on-unsupported-macs.2183772/page-428

**Comment by artkirienko** [comment]
## The Zoom application does not show any video during meetings
This is due to the latest Zoom versions requiring a Metal-compatible GPU for video rendering. To patch this out of the Zoom application, download and run the script located [here](http://dosdude1.com/catalina/zoomnonmetal.command.zip)

From FAQ here: http://dosdude1.com/catalina/
