### ISSUE TITLE
1Password crashes after applying patch from Patch Updater

### ISSUE THREAD

**Issue by ZebraDude** [dosdude1/macos-catalina-patcher#38]
I am running a iMac 11,2 ATI Radeon HD 4670 16GB RAM on Catalina Patcher on 10.15.4 patched with 1.4.0. I ran the Patch Updater (assuming that this push was 1.4.1) this morning and after reboot 1Password tried to start on boot and crashed with the below listed error data.

_________________________________________________________________________________
Process:               1Password 7 [595]
Path:                  /Applications/1Password 7.app/Contents/MacOS/1Password 7
Identifier:            com.agilebits.onepassword7
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           1Password 7 [595]
User ID:               502

Date/Time:             2020-04-08 05:11:31.463 -0500
OS Version:            Mac OS X 10.15.4 (19E266)
Report Version:        12
Anonymous UUID:        3EC79421-3A1D-E3ED-0630-6AECCA1B3EC2

Time Awake Since Boot: 300 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 0000000102262000-0000000102989000 [ 7324K] r-x/r-x SM=COW  

Thread 0 Crashed:
0   ???                           	0x0000000110d88000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffeed99dc50
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x0000000110d88000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0

Binary Images:
       0x102262000 -        0x102988fff +??? (0) <17CE8A8A-92C7-33A8-805F-44D995DE8DBF> (null)
       0x110d87000 -        0x110e18eff +??? (750.5) <1F893B81-89A5-3502-8510-95B97B9F730D> (null)

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 128
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=8788K resident=0K(0%) swapped_out_or_unallocated=8788K(100%)
Writable regions: Total=8480K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8480K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                            1404K        4 
__DATA_CONST                        20K        1 
__LINKEDIT                         880K        2 
__TEXT                            7908K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             74.0M       13 

Model: iMac11,2, BootROM 99.0.0.0.0, 2 processors, Dual-Core Intel Core i3, 3.06 GHz, 16 GB, SMC 1.64f5
Graphics: kHW_ATIM96Item, ATI Radeon HD 4670, spdisplays_pcie_device, 256 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1333 MHz, 0x0198, 0x393930353432382D3035312E4130304C4620
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1333 MHz, 0x0198, 0x393930353432382D3035312E4130304C4620
Memory Module: BANK 0/DIMM1, 4 GB, DDR3, 1333 MHz, 0x0198, 0x393930353432382D3035312E4130304C4620
Memory Module: BANK 1/DIMM1, 4 GB, DDR3, 1333 MHz, 0x0198, 0x393930353432382D3035312E4130304C4620
AirPort: spairport_wireless_card_type_airport_extreme (0x168C, 0x8F), Atheros 9280: 4.0.74.0-P2P
Bluetooth: Version 7.0.4f6, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: ST3500418AS, 500.11 GB
Serial ATA Device: OPTIARC DVD RW AD-5680H
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: IR Receiver
USB Device: Built-in iSight
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: BUP BK
USB Device: USB to Serial-ATA bridge
USB Device: Internal Memory Card Reader
USB Device: BRCM2046 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus:

**Comment by dosdude1** [comment]
This is covered in the FAQ. Run "sudo killall taskgated" in Terminal. This is an issue Apple introduced in 10.15.4, and nothing to do with the Patcher.

**Comment by LogoiLab** [comment]
Your issue has been closed because it is a common problem that can be remedied by taking the appropriate steps and reading instructions: http://dosdude1.com/catalina/

Your issue has also been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.

**Comment by TheAncientAnubis** [comment]
Mostly there is an signature failure in the app which cause a start error of the app, called "EXC_CRASH (Code Signature Invalid)" when you open the report. This can be fixed when removing the app signature and resign it on the local machine. After that the App should start on the first time, even after restarting the whole System. The Signatures maybe also get fixed, when you update or reinstall the app.

**Instructions to remove the signature and resign on the local machine:**

Open Terminal an type as follow to remove the signature of the app
**sudo codesign --remove-signature** _**"MyApp.app"**_
hit Enter and type your admin passwort then move on with enter

After that resign the app with.
**sudo codesign --sign -** _**"MyApp.app"**_
hit enter and your app should be permanently fixed. Test it.

_**"MyApp.app"**_ is a placeholder it should be replaced with the app name or simply drag an drop the targeted app in the terminal after tyou have typed the command to address it correctly as needed.

further instructions can also be found on:
[(https://eclecticlight.co/2023/06/05/what-to-do-when-an-app-crashes-as-it-opens/)]((https://eclecticlight.co/2023/06/05/what-to-do-when-an-app-crashes-as-it-opens/))
