### ISSUE TITLE
Apps not opening after restarting

### ISSUE THREAD

**Issue by pauloens77** [dosdude1/macos-catalina-patcher#39]
Microsoft Excel is not opening and crashes if I try to open. Couldn't open after upgrading to Catalina.
Everytime I restart the macbookpro 8,1 some apps crashes to open like Excel. Happened to Google Chrome, Busycal. Then if I restart sometimes comes back to work, only Excel is always crashing.

**Comment by pauloens77** [comment]
Thanks for the information, helped a lot. Sorry for taking your time about it.

**Comment by pauloens77** [comment]
Hello,
Do you know if this was solved on Catalina 10.15.5?

**Comment by TheAncientAnubis** [comment]
Mostly there is an signature failure in the app which cause a start error of the app, called "EXC_CRASH (Code Signature Invalid)" when you open the report. This can be fixed when removing the app signature and resign it on the local machine. After that the App should start on the first time, even after restarting the whole System. The Signatures maybe also get fixed, when you update or reinstall the app.

**Instructions to remove the signature and resign on the local machine:**

Open Terminal an type as follow to remove the signature of the app
**sudo codesign --remove-signature** _**"MyApp.app"**_
hit Enter and type your admin passwort then move on with enter

After that resign the app with.
**sudo codesign --sign -** _**"MyApp.app"**_
hit enter and your app should be permanently fixed. Test it.

_**"MyApp.app"**_ is a placeholder it should be replaced with the app name or simply drag an drop the targeted app in the terminal after tyou have typed the command to address it correctly as needed.

further instructions can also be found on:
[(https://eclecticlight.co/2023/06/05/what-to-do-when-an-app-crashes-as-it-opens/)]((https://eclecticlight.co/2023/06/05/what-to-do-when-an-app-crashes-as-it-opens/))
