### ISSUE TITLE
No "All Photos" in Photo App

### ISSUE THREAD

**Issue by amnesia106** [dosdude1/macos-catalina-patcher#4]
In Photos App there no "All Photos" on the left Top. This is the first topic in the library. 
Macbook late 2008

![Bildschirmfoto 2019-11-10 um 13 27 59](https://user-images.githubusercontent.com/40226796/68543942-f4dc4500-03bd-11ea-8b64-d844e4e05a77.png)

**Comment by User868** [comment]
Same Problem on my iMac Late 2009.
and no idea how to fix it :(

**Comment by LvanProosdij** [comment]
Same problem here iMac early 2008, French system

**Comment by LvanProosdij** [comment]
Even creating a new photo library gets the problem 
<img width="1023" alt="Capture d’écran 2019-12-16 à 16 56 03" src="https://user-images.githubusercontent.com/6991846/70921895-6fcff580-2025-11ea-8c52-0173eaedbbc5.png">

**Comment by PavelHolec** [comment]
Same here. On both MBP 2009 and 2011. Tried cleaning Photos cache, changing locale settings, creating new library, SMC reset... nothing.
Even the Display > Library menu starts lists from “memories” as ^1 option.

**Comment by JDHurt** [comment]
Exactly the same problem on one MBP 2009 and one Mac Mini. Trying to reinstalling from scratch but same problem after a restore from my TM backup. Strangely, same install went fine on a MacPro 3,1.

**Comment by PavelHolec** [comment]
The section is probably missing because it may be heavily metal-based, so the app gracefully ignores it.
Found the workaround for now: To access at least the legacy version of "All Photos", click on any photo and choose "Show in All Photos".

**Comment by JDHurt** [comment]
> Found the workaround for now: To access at least the legacy version of "All Photos", click on any photo and choose "Show in All Photos".
Working great! Thanks for the tip.

**Comment by chaoxia322** [comment]
Same Problem, MacBook Pro, Late 2011

**Comment by MrCee** [comment]
@dosdude1 I'm Using an iMac Mid 2010 21.5”, 3.06 GHz Intel Core i3, ATI Radeon HD 4670 256 MB (AKA 11,2) using the Catalina patcher and have the same issue as OP. 

Mojave patch worked beautifully for Mojave and Photos did not have a problem, but yes the most crucial part of Photos is missing for the current Catalina patcher. 

The end-user I am working with cannot go without the drill-down into years/months/days/All Photos and any above-mentioned workaround may not be entirely accurate as I may have been seeing "All Photos" from the particular subfolder I was viewing via legacy workaround and not All Photos from all time.

There were graphics issues I fixed using SwitchResX, but with the lack of the first "Photos" menu in the sidebar of Photos.app, I have had to revert back to Mojave patcher.

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/10969457/76217345-5e823800-6266-11ea-9d46-57b72eb5dd9b.png">

**Comment by RalfHS** [comment]
I have the same problem on a MacBook 5.1.
Will there be a correction to the problem?

**Comment by starmessage** [comment]
I have the same problem.
Here is a related discussion that might add some more info
https://discussions.apple.com/thread/250983092

**Comment by dunirap** [comment]
> Same problem here:
> 
>     * iMac early 2008, French system
> 
>     * was running flawlessly under Mojave since a few months thanks to macOS Mojave Patcher
> 
>     * has been updated to Catalina 10.15.1 using macOS Catalina Patcher 1.2.3 with "Install to this machine" installation method.
> 
>     * try to solve the bug by updating to Catalina 10.15.2 using macOS Catalina Patcher 1.3, unsuccessfully.
> 
> 
> <img alt="Capture d’écran 2019-12-16 à 16 51 24" width="291" src="https://user-images.githubusercontent.com/6991846/70921832-56c74480-2025-11ea-8edb-3498ae8b09ed.png">

Bonjour, avez vous trouvé une solution au problème , j'ai le même soucis, merci

**Comment by fraetezr** [comment]
Same problem here with
MacMini (2011)
Catalina 10.15.4

**Comment by PierreScerri** [comment]
Same problem with iMac 9.1 24" - Catalina 10.15.3

**Comment by Maksov** [comment]
same problem on macbok pro 2010mid. Is there a solution to this problem?
