### ISSUE TITLE
"The installer is damaged, and can't be used to install macOS" despite download from within Catalina Patcher

### ISSUE THREAD

**Issue by marcon89** [dosdude1/macos-catalina-patcher#40]
macbook7,1 running macos 15.3 via Catalina Patcher 1.3.4. 

USB flash stick install media newly formatted with "disk utility" and created from within Catalina Patcher with "download a copy..." and "create a bootable installer", followed immediately by an installation attempt. Latest attempt downloaded macos 15.4.02.

Installation of macos 15.4 via Catalina Patcher 1.3.5 or 1.4.1 terminated after selection of "reinstall macos" and "continue" with:
"The installer is damaged, and can't be used to install macOS"

Installation of 15.3 with Catalina Patcher 1.3.4 from macos High Sierra without problems.

Thank you.

**Comment by say8425** [comment]
duplicated with #20

**Comment by PG248** [comment]
Same here. "The installer is damaged, and can't be used to install macOS" message immediately after starting the installation bevor I can select the target drive.

Re-downloading the "Install macOS Catalina"-App via the patcher didn't help. It is version 15.4.02. Probably a new version that is not compatible with the Catalina Patcher.

**Comment by PG248** [comment]
My fault. I had not disabled SIP. After disabling SIP, the installation proceeded without issue. A warning that you have to disable SIP even when using a bootable installer drive might prevent others from running into the same issue.

**Comment by marcon89** [comment]
Same here. Disabling of SIP solved the problem. 

However, since the local recovery partition didn't work and internet recovery booted into the macos my mac came with (Lion), which didn't recognise "csrutil disable", I had to boot into the internet recovery mode for the latest supported macos of my macbook with "⌘+alt+r" during boot.
