### ISSUE TITLE
Zoom.us does not display video

### ISSUE THREAD

**Issue by marcon89** [dosdude1/macos-catalina-patcher#41]
macbook7,1 running macos 15.3 via Catalina Patcher 13.4.

Zoom.us app does not display video, but did do so in macos High Sierra. Complete removal and reinstall of both the app and macos did not fix this.

Could this be due to the lack of „Metal“ support in the macbook‘s graphics‘ chip?

Edit: Just to clarify, it's only the video streams from other people that aren't working. I only get a black window for them, just as if their camera was off. They can see me just fine. Audio works bi-directional.

I tested this in my own network, too.

**Comment by fe7ng654123** [comment]
> macbook7,1 running macos 15.3 via Catalina Patcher 13.4.
> 
> Zoom.us app does not display video, but did do so in macos High Sierra. Complete removal and reinstall of both the app and macos did not fix this.
> 
> Could this be due to the lack of „Metal“ support in the macbook‘s graphics‘ chip?

Having the same issue on my Macbook A1342

**Comment by candravenus** [comment]
me too, MacBook8,1 (A1278) running the latest patcher..

zoom.us app does not display my video n other, but other can see me.

**Comment by marcon89** [comment]
Solution by **dosdude1** on this closed thread:
https://github.com/dosdude1/macos-catalina-patcher/issues/36

> You need to use an older version of Zoom, that does not utilize Metal rendering (which the hardware in older machines does not support). A version that works can be downloaded here: https://d11yldzmag5yn.cloudfront.net/prod/4.5.5757.1110/Zoom.pkg
