### ISSUE TITLE
Killall taskgated doesn't always help

### ISSUE THREAD

**Issue by Allart79** [dosdude1/macos-catalina-patcher#42]
I have installed the patch, thanks for this! Also ran into the issue described, crashing apps when started. Now I've tried with some success to use "sudo killall taskgated" (this worked for office 365 for example). But it does not work for Chrome for example (error report below).
The common denominator seems to be: 
===================================================
Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1
===================================================
Any suggestions....? Or is this Apple?

Process:               Google Chrome [1174]
Path:                  /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Identifier:            com.google.Chrome
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Google Chrome [1174]
User ID:               501

Date/Time:             2020-04-13 23:21:10.552 +0200
OS Version:            Mac OS X 10.15.4 (19E266)
Report Version:        12
Anonymous UUID:        D222E284-41C9-4000-811B-748D9698C388

Time Awake Since Boot: 1700 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 0000000102ac9000-0000000102af3000 [  168K] r-x/r-x SM=COW  

Thread 0 Crashed:
0   ???                           	0x000000010aac1000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffeed136be8
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000010aac1000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0

Binary Images:
       0x102ac9000 -        0x102af2ff7 +??? (0) <0573EDDB-32F9-38D3-8237-C3344E615BB2> (null)
       0x10aac0000 -        0x10ab51eff +??? (750.5) <1F893B81-89A5-3502-8510-95B97B9F730D> (null)

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 787
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1004K resident=0K(0%) swapped_out_or_unallocated=1004K(100%)
Writable regions: Total=8408K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8408K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             232K        4 
__DATA_CONST                        20K        1 
__LINKEDIT                         252K        2 
__TEXT                             752K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             65.2M       13

**Comment by LogoiLab** [comment]
Your issue has been closed because it is a common problem that can be remedied by taking the appropriate steps or just reading instructions: http://dosdude1.com/catalina/

Your comment has also been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.
