### ISSUE TITLE
It appears that Catalina 10.15.4 removed my MacPro 5.1 wireless drivers.

### ISSUE THREAD

**Issue by PhilSE30** [dosdude1/macos-catalina-patcher#44]
It appears that Catalina 10.15.4 removed my MacPro 5.1 wireless drivers.
Running the patch with the initial Catalina release worked fine previously.
Giovanni Caporaletti & Mrugesh Mohapatra posted a solution to copy back the drivers from Mojave which fixed the issue. 
https://apple.stackexchange.com/questions/372025/missing-wifi-interface-after-upgrade-to-catalina?newreg=1904677ef3d840f0a87b73a2cd7bd342

Can they be included the next patch?

Thank you

Phil

**Comment by tachang** [comment]
I think this happened too but not entirely sure. My wifi was working on first boot but then it stopped working.

**Comment by LogoiLab** [comment]
We cannot include third party software in patches without the permission of the original author.
