### ISSUE TITLE
Catalina install hangs at the very end of install (grey background)

### ISSUE THREAD

**Issue by AdriVale** [dosdude1/macos-catalina-patcher#45]
Please only file an issue here for code-related problems. This is not an issue system for resolving issues with using the compiled binaries, or discussing functionality issues with Catalina on your unsupported machine.
- [X] I understand

Catalina won't finish its install process. Hangs when the progress bar is full (after the first reboot, grey background, black progress bar). 

Any advice on how to make it work? 

It's on a Mid 2009 13' MacBook Pro (500GB SSD and 4GB RAM)

**Comment by SimonSturmans** [comment]
I have the same problem on a MacBookPro8,1.

Any idea what might cause this?

**Comment by PhilGrue** [comment]
I've had the same issue yesterday.
At the end of the installation, where the white screen shows the full progress bar, but nothing happens, just unplug the imac. Wait 5 sec, then boot again. I think I had to do this an two different point at the end, but my imac is now running fine.

**Comment by PhilGrue** [comment]
Did you stick to the installation process that dosdude has shown in his video? And did you install the patches?

**Comment by AdriVale** [comment]
On my end, I left it with the progress bar à 100% for an hour, then turned it off, and booted again, and it successfully booted into Catalina. No idea, how, why, but in the end it "worked" somehow!

How you have any luck as well...

**Comment by Grix** [comment]
I also experienced this, with Mid-2011 mac mini

**Comment by blhouston** [comment]
13"  Macbook Pro - (the cheap one) same thing for me. Stopped at about 95% with fans running full bore.  Hard reboot and it launched right in to the proper UI.

**Comment by p4r4d0x86** [comment]
Grey background, progress bar at 100% for hours on a MacBook Pro 5.3 and 7.1
Forced power off, boot in Catalina on next boot.
So far, so good.

**Comment by ecoplace** [comment]
Similar experience. I just left it for about half an hour then did a forced power off. It then booted into Catalina

**Comment by michaelgregson** [comment]
Just to confirm as others experiences - same on a MacBook Pro 5,4. At end of install hung with filled progress bar. Left for an hour before force reboot and all working great. 

Thank you for the excellent tool.

**Comment by mpilgrem** [comment]
I also experienced this with a mid-2011 Mac mini (macmini5,1) and patcher version 1.4.4. Booted into Catalina after a forced power off. In between, I also removed a USB drive.

**Comment by xxDJSCxx** [comment]
I also experienced this freeze on my Macbook Air 13” (Late 2010), 3, 1. Just did force shut-down, rebooted it, made sure it booted to my SSD, and Catalina Start Up Screen showed up perfectly.

**Comment by LogoiLab** [comment]
Your issue has been closed because it is a common problem that can be remedied by taking the appropriate steps and reading instructions: http://dosdude1.com/catalina/

Your issue has also been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.

**Comment by mrirmak** [comment]
I had same issue with my Macbook Air 2011 Mid. Progress bar %100 and nothing happen. I waited 1-2 hours and restart force. 
Boom, it booted with no problem. Also, I un-plugged usb while restarting. Works well. Thanks

**Comment by zqmlk** [comment]
> 13" Macbook Pro - (the cheap one) same thing for me. Stopped at about 95% with fans running full bore. Hard reboot and it launched right in to the proper UI.

How to hard reboot? and by 95% you mean like at the end around a half a centimeter empty right?

**Comment by FastMaster678** [comment]
Shutting down the Mac and removing the USB installer, then booting back up worked for me, too
