### ISSUE TITLE
Time machine back up not working

### ISSUE THREAD

**Issue by lejonvanrhee** [dosdude1/macos-catalina-patcher#46]
I have tried to restore from time machine backup using the installer, it’s been stuck on one and a half hours for 3 hours and the progress bar doesn’t progress, needless to say, I don’t know what is going on.

-edit
Might be important to say that i have set up a fusion drive onto which I am recovering

**Comment by notsouren** [comment]
Macbook 7,1 and restore does nothing. Always says backup was done with an OS version higher than what you're running, which is nonsense as backup was done with the same machine 30mins ago.

**Comment by ppgiron** [comment]
MacBook Pro 5,5 - Unable to restore previous validated versions.  

- "Restore" button is inactive on all versions, even current backups (post-Catalina install).
- Finder window in Time Machine hangs when loading Backups.backupdb content.

**Comment by LogoiLab** [comment]
This is not an issue of catalina patcher itself.

Your issue has also been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.
