### ISSUE TITLE
Screen recording permission missing

### ISSUE THREAD

**Issue by Menniac** [dosdude1/macos-catalina-patcher#49]
Hey There! I`m using the Catalina patch on an iMac 8,1 (2,66 GHz, 6GB RAM). The system runs neatly so far. Thank you, Dosdude!
The first trouble I'm having concerns an app called Duet Display. It should make the iMac a second screen to my Windows notebook, but the app breaks down on the iMac when I start connecting the two machines. (No troubles on the Windows system.)
I did some research and found out that the app might be missing screen recording permissions on the iMac. Usually there should be a check box for the app in security preferences/screen recording, but it isn't on my Mac. I reinstalled the OS and the app. This didn't help. Check box is still missing.
Interestingly the app needs another permission in security preferences/accessibility. This permission is requested during the installation process (no pop up for screen recording though) and I can see the check box in the preferences afterwards.
Anyone having similar issues or any solutions?
I have an idea about the problem which might be wrong anyway: The support of the app told me that permitting screen recording is only necessary since Catalina. So I thought maybe the app is not 'noticing' that I'm running Catalina because it is not supported by my iMac.
I would be happy for any hints. Thanks a lot!

**Comment by LogoiLab** [comment]
Your issue has been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.
