### ISSUE TITLE
MacOS Catalina installer downloaded with Patcher fails verification

### ISSUE THREAD

**Issue by bmy** [dosdude1/macos-catalina-patcher#5]
The MacOS Catalina installer that Catalina Patcher downloads (which I confirmed with Little Snitch is coming straight from Apple's server) throws the usual error unsigned binaries do that it "can't be opened because the identity of the developer cannot be confirmed". 

This strikes me as odd. If you're on Mojave and upgrade the normal way using a supported machine, the installer file that downloads doesn't throw this error. Why isn't the Apple binary downloaded by Patcher signed by Apple? Has Patcher somehow modified this file, even if I've unchecked "Auto Apply Post Install Patches" ? For what it's worth, I saw an arguably more concerning error when I initially ran Patcher – one I've never seen thrown by another binary on MacOS – that it "can't be opened because Apple cannot check it for malicious software".

And in terms of verifying the integrity of the installer, I can't seem to find official SHA1 or MD5 hashes from Apple anywhere.

I needed this file after I'd upgraded to Catalina to install Catalina on another supported machine that's in a remote location without internet, , and Patcher seemed like a great way to get it...but I'll just need to verify that the installer hasn't been modified. Thanks!

**Comment by dosdude1** [comment]
The reason for that is that the method Catalina Patcher uses to "create" the app bundle from the downloaded files does not retain Apple's developer certificate. The app itself, and its resources, are unmodified from the stock copies. There is a page here where you can see the expected SHA1 sums of the two main installer resources (BaseSystem.dmg and InstallESD.dmg): https://github.com/notpeter/apple-installer-checksums
