### ISSUE TITLE
Video Playback and screen Error

### ISSUE THREAD

**Issue by nimaam** [dosdude1/macos-catalina-patcher#56]
First of All I am thank full.
I use Mac Pro 4,1 and after install Mac OSx Catalina with your patch, now I have problems:
1- In safari and Finder when I open new tab the tab screen become black and now show the text
2- In Applications Like VLC there is no video playback.

**Comment by dosdude1** [comment]
Upgrade to a modern, Metal-compatible video card (recommended), or apply the Legacy Video Card Patch.

**Comment by mattcline1** [comment]
Hi Dosdude,  I am also thankful for the work you've put in on this, you are truly incredible with these things.  I used your Catalina upgrade on my late 2011 MacBook Pro.  I primarily use the computer for music recording programs pro tools and Luna.  The install was successful but I had trouble getting my time machine backup to transfer back all my data and programs.  I was able to do it after pushing through some odd glitches.  Now I'm all set up but my luna program is glitching pretty bad.  when I open plug ins within the session I'm working on, it just shows me an outline of the plug in, none of the knobs I need inside are visible.   Any thoughts on a workaround for this or if I have done something wrong?

**Comment by nimaam** [comment]
I did the patch with display card legacy and now all problems that I mentioned is ok

**Comment by LogoiLab** [comment]
Your issue has been closed because it is a common problem that can be remedied by taking the appropriate steps or just reading instructions: http://dosdude1.com/catalina/

Your comment has also been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.
