### ISSUE TITLE
installation stalled (possibly at "updating dyld shared cache"), successful after forced poweroff

### ISSUE THREAD

**Issue by korakinos** [dosdude1/macos-catalina-patcher#58]
> Please only file an issue here for code-related problems. This is not an issue system for resolving issues with using the compiled binaries, or discussing functionality issues with Catalina on your unsupported machine.
> - [X ] I understand
> 

I used Catalina patcher on an early-2008 iMac -- ultimately succesfully it seems (~~apart from a display issue in Mail, but that is probably another issue~~[1]), but with a hickup that seems worth reporting. Also, I'm worried that something went wrong that could come back to bite me later.

At some late point in the installation (grey background, progress bar at 100%) progress completely stalled, even after letting the machine sit for more than 24 hours, after which I powered it down by holding down the power button. I did this twice:
 
 - The first time I had used a USB medium flashed from the old system on the same iMac, and I had chosen to "convert" the hard drive to APFS instead of deleting it at the beginning of installation. After having interrupted the installation, the computer booted up to a message saying that Mac OS cannot be installed/upgraded on this system, and booting from the USB drive didn't work anymore either, it appeared to be corrupted somehow. (I didn't write down the exact messages of this failed attempt, sorry.)

 - The second time I had flashed the USB drive from another Mac and "deleted" the hard drive to APFS. Installation on the iMac stalled and I interrupted it by holding the power button in the same way as before. However this time, the installation was successful, the computer booted into the newly installed Catalina. 

Because I was concerned that something hidden might be amiss with the installation, I booted from the USB drive again (which worked this time) and started the process of installing post-installion patches manually. This process stalled at the step `updating dyld shared cache`. I'm suspecting this is the same point at which it stalled earlier, only that that time I hadn't been able to see the message.

Should I be concerned about the state of my installation? 

[1]: Somehow mail body text was not being displayed with the font set to Helvetica. Changing the font made it visible.

**Comment by itsrobatlas** [comment]
Hi Korakinos, 

Weirdly enough, I'm trying to install this Catalina on a 2008 24" iMac too. I get it to do the installation but when I'm doing the patch it crashes on dyld shared cache. 

I can't get it to boot into Catalina at all or even boot any partition for an installer I have of other macOS either, I'm stuck with Catalina. But I cant for the life of me after powering it down etc to get it to boot. Can you let me know how you got around it booting ? Because I'm completely stuck.

Rob

**Comment by korakinos** [comment]
I did nothing special at all. As I wrote, I interrupted the stalled installation by holding down the power button of the iMac. Then I pressed the button again to start the machine up, and it booted into Catalina. The only two differences between this successful attempt and the one before were that 1) I chose the "erase" methode for formatting the hard drive instead of "converting" it (these two options are mentioned in the tutorial video[1], and that 2) I created the thumb drive on another Mac.

Maybe there is an element of randomness? You could just try again and see if that changes anything.

[1]: https://www.youtube.com/watch?v=wxFzZWqoCng&feature=emb_title

**Comment by itsrobatlas** [comment]
That's so weird. I installed on the 2008 iMac OSX Lion and had no issues worked perfectly. I have a bootable drive with all mac os and patches on for repairs. 

Went to install Catalina booted into the disk no problem, formatted the drive to apfs and installed Catalina no problem. Boot up into recovery to apply patches stalls on last bit on dyld cache. Turn off try and boot up normally loading macOS gets to about 2/3 and crashes for hours on end. 

Try to reinstall osx Lion and then the graphics don't display right and won't install that either. Cant boot a el capitan install, cant boot a high sierra patcher or anything. Only Catalina. Going to swap out the drive later as it appears there's a partition there what maybe causing my issue I cant seem to swap out. 

Got amazon coming to deliver some T9 torx etc so I can pop the screen off. Will update.

**Comment by itsrobatlas** [comment]
So i have an issue with my bootrom but cant for the life of me find a way to reset it

**Comment by korakinos** [comment]
Possibly related: https://github.com/dosdude1/macos-catalina-patcher/issues/45

**Comment by DieProgrammIDE** [comment]
How did you make your installation media, with your own Downloaded Catalina (if, with which version) or did you download it via the tool. When downloading via the Tool i get stuck, getting an error that "Reinstall MacOS" can't be started, with my own Catalina File, i am stuck on boot.

**Comment by itsrobatlas** [comment]
I can install with no issues on Mojave but it won’t boot, if I install Catalina I get no problems but when I patch I get stuck on Dyld cache. Can’t boot it at all. If I try and install any other os eg el cap won’t load the installer if I load lion what worked fine the graphics are displaying badly like the gpu is corrupt. But Catalina and Mojave installers look fine. 

Bit annoyed with myself because I can’t get it to do anything and I need to ship the iMac out.

**Comment by DieProgrammIDE** [comment]
Odd, so the original apple installer with no patches doesn't work for El Capitan? I hope i don't run into that problem, as i deleted the working El Capitan

**Comment by itsrobatlas** [comment]
Can’t do anything at all. I changed the hdd. It worked perfect before Catalina patcher. Can’t get it to do shit

**Comment by itsrobatlas** [comment]
I’ll post picture shortly

**Comment by itsrobatlas** [comment]
So take a look at images below -

**Boot screen choosing which drive - Displays corect**
[https://robatlas.com/catalina/1.jpeg](url)

**Boot OSX Lion installer which was previously running fine prior**

[https://robatlas.com/catalina/2.jpeg](url) 

**Boot Mojave installer or Catalina installer displays correctly** 

[https://robatlas.com/catalina/3.jpeg](url)

Mojave will install, will patch fully no issues. Installer takes a while but it gets there. 

Catalina will install no problems but wont patch gets stuck on dyld cache and leave for hours even mouse is unresponsive. If force reboot into Catalina afterwards get stuck on white with grey bootscreen at about 60% and that's it dead for hours. 

If I try to install El Capitan maximum compatible for that mac, gets to 60% on loading the drive for the installer and does nothing. Apple bootable drive from their website no issues and works on other machines. 

Just stuck for ideas. Cant get it to do anything.

**Comment by DieProgrammIDE** [comment]
I solved all of my problems by Creating and Downloading Catalina from Catalina Patcher on My iMac 2017 (testing if it worked via the iMac 2017), installing Catalina on the Early-2008 iMac. Before continueing install after reboot i booted into Recovery from the USB and applied the patches with cache rebuild. Then Catalina was installed till it stuck with a full bar. I disconnected power for 15 Seconds (SMC Reset) then turned it back on and Ét voila, Catalina Setup shows up!

**Comment by p4r4d0x86** [comment]
Grey background, progress bar at 100% for hours on a MacBook 5.3 and 7.1
Forced power off, boot in Catalina on next boot.
So far, so good.

**Comment by itsrobatlas** [comment]
Will update today, going to give this a go and see what I can get it to do :)

**Comment by Feellips** [comment]
Got this issue. Macbook Air 2009 Mid (2.1), stuck at 95% reboot doesn't help, it's just restarts the installation process.

**Comment by itsrobatlas** [comment]
I couldn’t get it to work under any circumstance. Can’t install anything other than Mojave and even that won’t boot. 

I ended up swapping the board out and installing el cap again. Was a bit annoying. Maybe an efi chip replacement maybe the job

**Comment by rich1015** [comment]
I got the same issue with the installation process stalling at full progress bar, but Catalina working after a forced shut down.

But my system seems to keep getting stuck on various processes at the very end:
1) at the end of re-installing the patches via the Patcher tool. It looks fine, progress bar is by full, pop up to restart now or later opens. After hitting „restart now“, the ‚restart now or later‘ window closes, but progress bar is still shown and the Mac won’t reboot.
2) trying to install Xcode through the App Store. After the download is completed, the process got stuck while displaying „installing...“

Mid 2011 MacBook Air

**Comment by LogoiLab** [comment]
Your issue has been closed because it is a common problem that can be remedied by taking the appropriate steps and reading instructions: http://dosdude1.com/catalina/

Your issue has also been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.
