### ISSUE TITLE
Problem with Microsoft Office

### ISSUE THREAD

**Issue by nimaam** [dosdude1/macos-catalina-patcher#59]
Dear All
I faced with a problem, after install the Microsoft office with or without serializer, it brings me the error of signature and I can not solve the problem till now.
but with the same source in my Macbook pro 2017 no problem
Could you please help me????

**Comment by richardmayer** [comment]
After running this in the Terminal, all the office applications run fine for me:

sudo nvram boot-args=amfi_get_out_of_my_way=0x1

Best Regards

Richard

**Comment by daert** [comment]
Try:
sudo defaults write /Library/Preferences/com.apple.security.libraryvalidation.plist DisableLibraryValidation -bool true
and then rebbot

**Comment by nimaam** [comment]
Its solved with your help thanks alot
