### ISSUE TITLE
Startup disk icon issue

### ISSUE THREAD

**Issue by Jaroslav84** [dosdude1/macos-catalina-patcher#6]
![Screenshot 2019-12-08 at 17 40 14](https://user-images.githubusercontent.com/1220870/70385503-4b9b6580-19e2-11ea-809a-815f7caea688.png)

I have an issue where the **startup disk icon** looks like a folder icon.
I tried everything to change it. No success. 

Anyone faced the same issue?
It's really annoying because it has other weird system side-effects.

I have to admit that I'm using RAID 1 with two SSD's, HSFP.

**Comment by Jaroslav84** [comment]
ok, **_startup icon_** issue is fixable if you have same drive name in:

```
/Volumes/Drive_Name
```
and in
```
/System/Volumes

**Comment by LogoiLab** [comment]
This does not seem to be an issue related to the patcher but to your hardware. Something is off somewhere with your system in particular. This issue cannot be replicated and is therefor too narrow.
