### ISSUE TITLE
Various apps won't start 

### ISSUE THREAD

**Issue by dstoffers** [dosdude1/macos-catalina-patcher#62]
After patching 10.15.5 (1.4.4) and 10.15.4 (1.4.3) and restoring from TimeMachine various apps often don't start. The behavior is also inconsistent, sometimes apps do start. When I go back to 10.15.3 everything is perfectly fine. Any clues?

**Comment by apkalexei** [comment]
Apply this command: sudo nvram boot-args=amfi_get_out_of_my_way=0x1

**Comment by dstoffers** [comment]
Thanks, will give that a try ASAP

Fumbled from my phone

**Comment by artkirienko** [comment]
Re-opening immediately after crash works for me

## Hardware and software
![84833720-9c96b100-b038-11ea-87d5-1ba5a2c47a18](https://user-images.githubusercontent.com/2473081/85129703-4003e380-b23c-11ea-8d74-d9f423bdc975.png)

## Examples
![Screenshot 2020-06-16 at 22 10 42](https://user-images.githubusercontent.com/2473081/85129775-5e69df00-b23c-11ea-8e7c-f5da9d467f46.png)

![Screenshot 2020-06-18 at 18 57 27](https://user-images.githubusercontent.com/2473081/85129786-63c72980-b23c-11ea-9b6e-50c71ee8a6fe.png)

![Screenshot 2020-06-18 at 18 57 34](https://user-images.githubusercontent.com/2473081/85129795-67f34700-b23c-11ea-85bb-0b1598e3fb4d.png)

**Comment by TheAncientAnubis** [comment]
Mostly ther is an signature failure (also seen in the screen on the above post "EXC_CRASH (Code Signature Invalid). This can be fixed when removing the app signature and resign it on the local machine. After that the App should start on the first time, even after restarting the whole System. The Signatures maybe also get fixed, when you update or reinstall the app.

**Instructions to remove the signature and resign on the local machine:**

Open Terminal an type as follow to remove the signature of the app
**sudo codesign --remove-signature** _**"MyApp.app"**_
hit Enter and type your admin passwort then move on with enter

After that resign the app with.
**sudo codesign --sign -** _**"MyApp.app"**_
hit enter and your app should be permanently fixed. Test it.

_**"MyApp.app"**_ is a placeholder it should be replaced with the app name or simply drag an drop the targeted app in the terminal after tyou have typed the command to address it correctly as needed.

further instructions can also be found on:
[(https://eclecticlight.co/2023/06/05/what-to-do-when-an-app-crashes-as-it-opens/)]((https://eclecticlight.co/2023/06/05/what-to-do-when-an-app-crashes-as-it-opens/))
