### ISSUE TITLE
Google Chrome won't start and 10.15.5 supplemental update won't load

### ISSUE THREAD

**Issue by Elvis-Budingensis** [dosdude1/macos-catalina-patcher#63]
I run a late 2011 MacBook Pro 13" 2,4GHz with 16GB Ram and 10.15.5

Google Chrome won't start (I attached the report) and the supplemental update from June 1st would not load and install at all. Software actualization doesn't even show it though it is not installed!

But: your patch is great and I appreciate your hard work for us!
[chrome issue.txt](https://github.com/dosdude1/macos-catalina-patcher/files/4722371/chrome.issue.txt)

**Comment by danielbmay** [comment]
I have a late 2011 MacBook Pro 13" 2.4 GHz with 4 GB RAM and 10.5.5, and I'm experiencing the same issue. I can also attach the report if that would be helpful.
I installed Chrome on High Sierra then updated. I don't recall if I actually opened it on High Sierra or not before upgrading.

**Comment by giovalife** [comment]
Here, my experience on Macbook Pro 15 late2011.
First try, updated MacOS form Mojave (Mojave was perfect), now on Catalina some third party apps won't launch at all (included Chrome)...
Second try, Clean installed Catalina, better experience but same errors on third party Apps, but now MacOS report the error and the "workaround" mentioned in "Catalina Patcher FAQ" works and the apps now launch, it's annoying but it works...
Hope in future patch.

**Comment by ubik3000** [comment]
For me, I had the same issue, after update to 10.15.5, Chrome did not started with the same issue as exposed in "chrome issue.txt". Seems that restarting Chrome after a shutdown (restart also probably works) solved the issue.

**Comment by danielbmay** [comment]
I ran the code listed in another issue, and still had the issue.
`sudo nvram boot-args=amfi_get_out_of_my_way=0x1`
I deleted and reinstalled Chrome, and it crashed upon startup. Tried to reopen it immediately and it worked. I'm posting using Chrome. Hoping it keeps working.

**Comment by giovalife** [comment]
my temporary solution is keep Chorme as a login element hidden...it boot up with MacOS and does not crash at all in your session...
(MacBook Pro 8.2 - Clean Catalina install)

**Comment by ubik3000** [comment]
Actually this worked for me. Also I did a restart.
> I deleted and reinstalled Chrome, and it crashed upon startup. Tried to reopen it immediately and it worked. I'm posting using Chrome. Hoping it keeps working.

**Comment by artkirienko** [comment]
Re-opening immediately after crash works for me

## Hardware and software
![84833720-9c96b100-b038-11ea-87d5-1ba5a2c47a18](https://user-images.githubusercontent.com/2473081/85129703-4003e380-b23c-11ea-8d74-d9f423bdc975.png)

## Examples
![Screenshot 2020-06-16 at 22 10 42](https://user-images.githubusercontent.com/2473081/85129775-5e69df00-b23c-11ea-8e7c-f5da9d467f46.png)

![Screenshot 2020-06-18 at 18 57 27](https://user-images.githubusercontent.com/2473081/85129786-63c72980-b23c-11ea-9b6e-50c71ee8a6fe.png)

![Screenshot 2020-06-18 at 18 57 34](https://user-images.githubusercontent.com/2473081/85129795-67f34700-b23c-11ea-85bb-0b1598e3fb4d.png)

**Comment by Elvis-Budingensis** [comment]
Hi,

my Catalina 10.15.5 on my MacBook Pro 13“ Late 2011 doesn’t show the possibility to upgrade to 10.15.6.

Does anybody know a fix for this?

All the best,
Daniel

**Comment by LogoiLab** [comment]
Your issue has been closed because it is a common problem that can be remedied by taking the appropriate steps or just reading instructions: http://dosdude1.com/catalina/

Your comment has also been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.

**Comment by rafaelpegadodasilva** [comment]
SOLUTION - CHROME AND OFFICE, TERMINAL CODES IN VIDEO DESCRIPTION.
https://www.youtube.com/watch?v=NLcRBxmPt8U

**Comment by cybanjar** [comment]
> SOLUTION - CHROME AND OFFICE, TERMINAL CODES IN VIDEO DESCRIPTION.
> https://www.youtube.com/watch?v=NLcRBxmPt8U

Thank's. Solve
