### ISSUE TITLE
Can not enable Safari Extensions 

### ISSUE THREAD

**Issue by m4d-maNu** [dosdude1/macos-catalina-patcher#64]
Hi,
I can not enable Safari Extensions, is this a bug/problem because of I Use Catalina Patcher or is this a Catalina Problem?

**Comment by int3nz0r** [comment]
+1

**Comment by druby-luke** [comment]
I'm having the same problem, tried it on two macbook pro7.1's and a macbook pro 5.2. 

They all wont let me enable extensions. I tried Adguard and adblock plus both from the app store and another adguard version without the app store.

**Comment by artkirienko** [comment]
**Confirmed** (good thing I don't use Safari daily)

## Hardware & software
![Screenshot 2020-06-16 at 23 14 44](https://user-images.githubusercontent.com/2473081/84823551-33f30880-b027-11ea-929c-5654f34ecb0e.png)

## Extensions I installed a minute ago
![Screenshot 2020-06-16 at 23 11 48](https://user-images.githubusercontent.com/2473081/84823558-381f2600-b027-11ea-9f7b-9db0bf9708f2.png)

## The problem
![Screenshot 2020-06-16 at 23 14 25](https://user-images.githubusercontent.com/2473081/84823690-70beff80-b027-11ea-91d3-1e2270733682.png)

**Comment by druby-luke** [comment]
I would suggest removing the serial number. @artkirienko

**Comment by artkirienko** [comment]
@druby-luke true. My bad, first time in a while 😞

**Comment by artkirienko** [comment]
Duplicate https://github.com/dosdude1/macos-catalina-patcher/issues/29

**Comment by Ebrakbr** [comment]
> I would suggest removing the serial number. @artkirienko

Could you please explain how can we remove the serial number?

**Comment by int3nz0r** [comment]
> > I would suggest removing the serial number. @artkirienko
> 
> Could you please explain how can we remove the serial number?

He/she means that you should blur your Mac's serial number in any screenshots you post. Not **actually** removing the serial number, that's not possible, and has nothing to do with this issue ;)
