### ISSUE TITLE
Mac OS download path pointing to symlink not resolved

### ISSUE THREAD

**Issue by mixage** [dosdude1/macos-catalina-patcher#65]
DownloadMacOSView.m

- (IBAction)startDownloading:(id)sender {
    ...
    
downloadPath = [NSHomeDirectory() stringByAppendingPathComponent:@"Downloads"];
	
**// MISSING:**
_NSDictionary *attr = [[NSFileManager defaultManager] attributesOfItemAtPath:downloadPath error:nil];
	if ( [[attr valueForKey:NSFileType] isEqualToString:NSFileTypeSymbolicLink] )
		downloadPath = [[NSFileManager defaultManager]_ destinationOfSymbolicLinkAtPath:downloadPath error:nil];
 ...
}

**Comment by LogoiLab** [comment]
Feel free to open a pull request with a fix. We are a tiny team and I'm just here to clean up the ridiculous amount of off-topic issues.
