### ISSUE TITLE
Delete APFS patcher after installation

### ISSUE THREAD

**Issue by bettinz** [dosdude1/macos-catalina-patcher#70]
Hello, is it possible to remove the APFS patcher after the installation?
I don't need it and it slow down the startup with verbose logs.

Thanks

Please only file an issue here for code-related problems. This is not an issue system for resolving issues with using the compiled binaries, or discussing functionality issues with Catalina on your unsupported machine.
- [X] I understand

**Comment by joevt** [comment]
Remove the bootx64.efi (774 KB), apfs.efi, startup.sh files from the EFI folder. Use Startup Disk preferences panel or whatever to make sure the current boot is set correctly.

**Comment by methanoid** [comment]
Given the only things in EFI are bootx64.efi, apfs.efi and startup.nsh (not .sh) I deleted them and machine fails to boot (throwing up the folder missing icon thing...

Is there a proper fix?

**Comment by joevt** [comment]
> Given the only things in EFI are bootx64.efi, apfs.efi and startup.nsh (not .sh) I deleted them and machine fails to boot (throwing up the folder missing icon thing...
> 
> Is there a proper fix? EDIT I am not using an APFS partition just MacOS Extended Journaled so I should not need the APFS patch?

I fixed the nsh spelling mistake. Thanks for pointing that out.

You booting Catalina from MacOS Extended? I don't think that's possible.

If you can't boot, hold the Option key down to select something else. Then fix whatever is broken.

**Comment by methanoid** [comment]
I ended up installing Mojave...  I was pointing out that the instructions just caused my machine to NOT boot... Are you suggesting those instructions with typo fixed WORK????
