### ISSUE TITLE
Created Installer USB Stick not bootable

### ISSUE THREAD

**Issue by martinjankoehler** [dosdude1/macos-catalina-patcher#71]
Please only file an issue here for code-related problems. This is not an issue system for resolving issues with using the compiled binaries, or discussing functionality issues with Catalina on your unsupported machine.
- [x] I understand

Given 
   - Running Mojave
   - macOS Catalina Patcher 1.4.4

I tried to use the "macOS Catalina Patcher" to "create a bootable installer"
![Screenshot 2020-06-17 at 19 38 44](https://user-images.githubusercontent.com/29398377/84930815-29417d80-b0d2-11ea-9efe-4222b97bb6ec.jpg)

However, the file system is not journaled and not bootable:
![Screenshot 2020-06-17 at 19 34 34](https://user-images.githubusercontent.com/29398377/84930445-943e8480-b0d1-11ea-8378-16809158532d.jpg)

**Comment by hairypalm** [comment]
I have the same issue.  Trying to boot from install media proceeds for a while with the progress meter under Apple logo, then locks up with the "X" image.  My machine is a Mac7,1 with the processor upgrade that is described as compatible.

**Comment by hairypalm** [comment]
> I have the same issue.

My bad -- it seems that Macs cannot boot every USB.  I just tried a different USB key and it booted with no problem at all.  Great patcher!

**Comment by humstrum** [comment]
Hi, could you please detail the brand and model and capacity of USB stick which worked? Thanks.

**Comment by LogoiLab** [comment]
Your issue has been closed because it is a common problem that can be remedied by taking the appropriate steps or just reading instructions: http://dosdude1.com/catalina/

Your comment has also been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.
