### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by startergo** [dosdude1/macos-catalina-patcher#79]
When I build the project it only builds patcherd nothing else.
![image](https://user-images.githubusercontent.com/7897244/88479978-1025bb00-cf21-11ea-9268-b911a3f45b28.png)

**Comment by dosdude1** [comment]
You have APFS Boot Selector set as your active build scheme, chance it to "macOS Catalina Patcher" and it should work. You may have to disable/chance codesigning settings as well.
![Screen Shot 2020-07-26 at 1 14 24 PM](https://user-images.githubusercontent.com/23435713/88485181-fa74bd80-cf41-11ea-873e-e031f6af4598.png)
