### ISSUE TITLE
MacMini 3.1 - LiveUSB installer hangs on Apple logo - progress bar not moving

### ISSUE THREAD

**Issue by AndrzejL-eu** [dosdude1/macos-catalina-patcher#82]
Hi there.

I have followed the instructional video here:

https://www.youtube.com/watch?v=wxFzZWqoCng

I have created a Catalina LiveUSB installer.

The installer works 100% - when I used it on my Macbook 8.2 it booted right into installer.

I then tried using this exact same LiveUSB on my MacMini 3.1 and it failed to boot.

_I am turning on MacMini with the pendrive plugged in. I am pressing the ALT key on the keyboard which takes me to boot menu. I am choosing the EFI Boot from the USB drive and I can see Apple logo with progress underneath but the progress bar does not move - at all. Then the machine reboots and shows me information that the MacMini was rebooted because of a problem and tells me to wait - then continues booting into Sierra._

I tried the following steps to resolve the issue.

I have created a Sierra LiveUSB using DosDude1's patcher.

I have booted and successfully installed Sierra on the MacMini 3.1 - works fine.

I have then followed this set of instuctions:

"APFS BootROM Support: If you have a machine that supports High Sierra natively, you MUST ensure you have the latest version of the system's BootROM installed. If you have NOT previously installed High Sierra, you can download and install this package (if running OS X 10.10 Yosemite or later) to install the latest BootROM version (you MUST reboot after installing the package to apply the firmware update). When installing, ensure your system is plugged in to power, or the update will not be installed."

From the "Important Info" section here:

http://dosdude1.com/catalina/

The installer said that the installation was successful. I rebooted the machine. The issue persists.

I Googled to find similar issues / solution but to no avail.

Thanks in advance for any help provided.

Kind regards.

**Comment by AndrzejL-eu** [comment]
I was told to try different pendrives. I tried 5 of them. Different brands. Different sizes. Some USB 2.0 some 3.0 - no change.

Any other ideas?

Kind regards.

**Comment by AndrzejL-eu** [comment]
Ok - tried few more pendrives. No go.

I can create Sierra and High Sierra installers on any of the pendrives using the dosdude1 patchers - they just work. I am installing High Sierra on APFS now (this very second).

Mojave and Catalina pendrives work fine on MacBook 8.2 but not on MacMini 3.1...

I am guessing something has changed either in the Mojave / Catalina itself or in the patchers for them and that causes the pendrive not to boot on MacMini 3.1. I know. Weird world - lotsa changes... Maybe MacMini is just not compatible as advertised? Is it because it has NVidia graphics? Maybe...

Let me know if you come up with any ideas guys because at this stage - this is a monologue...

Kind regards.

**Comment by AndrzejL-eu** [comment]
Ok monologue continues...

I was told to try external hard drive rather then pendrive.  SSDs and Spinning Rust were tested with a known working 100% USB to SATA cable. Nothing. There are 2 leds on the controller. Red and blue. Red - power. Blue - drive activity. At the beginning the blue led is blinking (just like on pendrives) and then led is on - all the time. It stays like this for a while. Then blue led turns off and it stays like that. No installer.

Kind regards.

**Comment by AndrzejL-eu** [comment]
I forgot to mention - I had an older version of Mojave install app and the patcher that goes with it - created a drive. No installer was reached either. I believe the Mojave installer + patcher were downloaded in first half of 2019. I might have to stick to High Sierra... I will keep trying tho...

Kind regards.

**Comment by LogoiLab** [comment]
Your issue has been closed because it is a common problem that can be remedied by taking the appropriate steps and reading instructions: http://dosdude1.com/catalina/

**Comment by AndrzejL-eu** [comment]
Guys, I've figured out installer "freezes" at

`PCI Configuration Begin`

Got it to boot in verbose mode. It freezes (as in won't continue) right after that.

![IMG_0243](https://user-images.githubusercontent.com/12524148/99913496-f9854a00-2cef-11eb-948a-5b3154772737.jpeg)
