### ISSUE TITLE
Detect Display Not Show

### ISSUE THREAD

**Issue by Zaboy15** [dosdude1/macos-catalina-patcher#83]
Please only file an issue here for code-related problems. This is not an issue system for resolving issues with using the compiled binaries, or discussing functionality issues with Catalina on your unsupported machine.
- [ ] I understand
Previously, my device was Macbook Pro 2011, when I was in Sierra OS the external display was still running normally using the mini display to hdmi converter, but when I upgraded using Catalina from Dosdude, the detect display in the settings menu didn't appear. please help, is it possible to use the dosdude version of catalina to use the extenal display?

**Comment by joevt** [comment]
Press the Option key to make the Detect Display button appear?
Or use SwitchResX which has a Detect Display menu item.

**Comment by Zaboy15** [comment]
Detec Display button is appear , but External Display still not connected . and i got erorr . 
[ERROR] - Unknown CGXDisplayDevice: 0x41dc9d00

**Comment by joevt** [comment]
The website at http://dosdude1.com/catalina/ says the following:

- AMD/ATI Radeon HD 5xxx and 6xxx series graphics acceleration: Currently, it is not possible to achieve full graphics acceleration under Catalina on any machines that use a Radeon HD 5xxx or 6xxx series GPU. If you have a machine with one of these GPUs installed, I'd advise upgrading it if possible (can be done in 2010/2011 iMacs, iMac11,x-12,x), disabling the dedicated GPU if using a 2011 15" or 17" MacBook Pro (MacBookPro8,2/8,3, instructions to do so can be found at http://dosdude1.com/gpudisable/ ), or not installing Catalina. Running Catalina without full graphics acceleration will result in extremely poor system performance.

The website at https://doslabelectronics.com/Demux.html says the following:
- DisplayPort is a functionality of the dedicated GPU only, disabling the dedicated GPU will also disable the DisplayPort.

Does your 2011 MacBook Pro have a Radeon HD 5xxx or 6xxx?
Did you disable the dGPU?

I don't think there is a fix for this problem.

**Comment by Zaboy15** [comment]
this specification display my macbook pro . 
Intel HD Graphics 3000 512 MB graphics

**Comment by joevt** [comment]
Please report the exact model of your 2011 MacBook Pro (13 inch or 15 inch or 17 inch, early or late 2011). The model is shown in "About This Mac"

The Apple tech specs website says all those MacBook Pros have HD 3000 graphics with 384 MB of shared memory. The 15 and 17 inch models also have AMD graphics (I think you need to force dGPU to see that info).
https://support.apple.com/en_US/specs/MacBook%2520Pro%25202011
https://gfx.io

**Comment by LogoiLab** [comment]
Your issue has been closed because it is a common problem that can be remedied by taking the appropriate steps or just reading instructions: http://dosdude1.com/catalina/

Your comment has also been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.

**Comment by Haschich** [comment]
I lost the external display functionality in a 13''. Does somebody know what to do? I already tried applying the patch again and can't get it to work. The display is detected, but no video is sent through the cable ("no signal" on the screen). Tried different adapters, cables, and monitors.
