### ISSUE TITLE
External Display, only in Safe Mode 

### ISSUE THREAD

**Issue by rtkuca** [dosdude1/macos-catalina-patcher#86]
I have a macbook 5.2 mid 2009, and I can only use two monitors (mini DVI > DVI) in safe mode, when I try the normal mode I can't get out of the admin login screen

**Comment by Fillelii** [comment]
I have a similar issue. The computer works fine until i connect an external monitor (have tried both hdmi/vga to Mini DisplayPort, and when i connect the monitor I’m thrown out to the login screen. When I enter my password the screen turns black for a few seconds and evetually goes back to the same login page again. If i disconnect the display I immediately can log in as normal. 

I’m using a 20inch iMac9.1 (early2009). The strange thing is that i also have another iMac9.1 with 24inch display also running patched Catalina and there it works fine.

**Comment by Fillelii** [comment]
I never found a solution, in fact I didn’t really try. I also sold the computer shortly after due to other reasons so unfortunately I won’t be able to research it further. The 24-inch model I still have and that one still works as expected.
