### ISSUE TITLE
Bootable installer doesn't boot on Macbook Pro 17" 2011

### ISSUE THREAD

**Issue by segers909** [dosdude1/macos-catalina-patcher#87]
Please only file an issue here for code-related problems. This is not an issue system for resolving issues with using the compiled binaries, or discussing functionality issues with Catalina on your unsupported machine.
- [ X] I understand

The installer shows up in the boot menu on the Macbook, but the progress bar just never fills entirely, the Mac doesn't boot into the installer. I've tried a different USB drive, tried re-downloading both Catalina and the patcher. I'm creating the bootable USB on a Mojave system.

**Comment by LogoiLab** [comment]
Your issue has been closed because it is a common problem that can be remedied by taking the appropriate steps and reading instructions: http://dosdude1.com/catalina/

**Comment by daslicht** [comment]
>reading instructions: http://dosdude1.com/catalina/
not true for my 2008 MBP
