### ISSUE TITLE
EFI issues: Option key does never start Startup Manager

### ISSUE THREAD

**Issue by vitalz** [dosdude1/macos-catalina-patcher#91]
MacbookPro5,2

When Option key is pressed and/or held then Startup Manager will never start - even there is an external bootable disk attached via USB.

_OS Patch manual_ also tells nothing about multi-boot abilities for any model: if this is possible, limited or impossible. There is also no manual for a case a user puts a second bootable disk in Data Doubler (yet: if that disk has Linux Mint it seems it will boot Mint always).

Also imagine a use case Data Doubler disk has El Captain MacOS with Windows 7 and the primary disk has Catalina patched installed: how is to switch between them?

Probably, EFI loader needs improvements. 

P.S. NVRAM, PVRAM, SMC resets didn't resolve issues described.

**Comment by joevt** [comment]
Option key happens before anything the Catalina patcher can change. Reset NVRAM harder.

Try Option key of separate USB keyboard?

**Comment by LogoiLab** [comment]
Your comment has been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.

**Comment by vitalz** [comment]
@joevt Isn't Terminal command in Recovery mode enough to reset NVRAM?
```
nvram -c
```
I noted that at first patched Catalina boot it set its disk into NVRAM like something permanent to boot (as I understood).
Also I used external Apple USB keyboard: it didn't help anyhow.

I assume my Macbook might have broken and repaired NVRAM module, etc. but nobody has told me any indicators of that. On macrumors forum I met posts people had similar problem on the other mac models.

**Comment by joevt** [comment]
To reset nvram - hold Command-Option-P-R until it boots. Keep holding it until it does that a one more time.
https://support.apple.com/en-ca/HT204063
https://support.apple.com/en-ca/HT201295

I don't know if `nvram -c` clears the same stuff.

I don't know of a way that makes Option key at startup stop working as it has in your case.
