### ISSUE TITLE
Update Catalina patch manual: add mentions on Homebrew and Docker workarounds

### ISSUE THREAD

**Issue by vitalz** [dosdude1/macos-catalina-patcher#92]
**Update patch manual**: add instruction/mention on **Homebrew** and **Docker**.

Some **Homebrew** packages will not install normally: for example, popular _python_ and _pip_ will fail to install and even might cause os system failure. (Seems _openssl_ package will be also broken.)
As a **workaround** a user has to change _Homebrew/Library/Homebrew/hardware.rb_ (a file also might depend on _brew_ version) to use _:core2_ instead of _:nehalem_ and then has to run _brew install_ with _--build-from-source_ or _-s_ flag only.

```
brew install --build-from-source python
```
```
brew install -s python
```

**Docker Desktop** doesn't run CPU with no hypervisor (for example, Core 2 Duo).
In this case users have to use [docker-machine with virtualbox](https://medium.com/crowdbotics/a-complete-one-by-one-guide-to-install-docker-on-your-mac-os-using-homebrew-e818eb4cfc3). This works.

**Nothing of that is mentioned anyhow in OS Patch manual.**

**Comment by SolidStill** [comment]
@vitalz 

> As a **workaround** a user has to change _Homebrew/Library/Homebrew/hardware.rb_ (a file also might depend on _brew_ version) to use _:core2_ instead of _:nehalem_ and then has to run _brew install_ with _--build-from-source_ or _-s_ flag only.

And, further, it may be necessary to build dependencies from source; and build the dependencies of the dependencies from source, and so on and so forth.

Q: Do you know how to do build the "dependency hierarchy" from source in a more concise way than manually checking for dependencies and building?

**Comment by vitalz** [comment]
@SolidStill If you have already improperly installed packages you need to run at least:
```
brew install -s $(brew list)
```

**Comment by LogoiLab** [comment]
Your issues with docker is because your CPU does not support newer virtualization CPU instruction sets.

Your comment has also been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for patcher code-related problems only.

**Comment by vitalz** [comment]
@LogoiLab This issue is not about Docker/Homebrew. This is about README.md file of Catalina patch: at least, it should tell end-users like in one or two sentences that a user will need well-known workarounds for these popular software products.

**Comment by LogoiLab** [comment]
@vitalz A user should be aware of their hardware's limits. This particular issue is seen across every operating system, on thousands of different devices. This is not a "just the patcher" issue. Most if not all virtualization applications tell you about this compatibility issue up front.

**Comment by vitalz** [comment]
@SolidStill 

_brew_ example for MacBook Pro 2009 17":
```bash
brew install  --build-bottle --bottle-arch=core2 docker
```
But it is a problem to maintain _brew_ packages because when a being install package (a bottle) has dependences then these deps need to be built and installed before this package installation. 

**Use MacPorts** instead of _brew_ because it uses different architecture concept: it builds a package on a machine where it is being installed. As a matter of fact I have had much better experience with Ports on patched OSX.
